import{describe,it,expect,vi}from'vitest';import{promises as fs}from'node:fs';import path from'node:path';import os from'node:os';
import{createApp}from'../server/app';import{Runtime}from'../server/runtime';import{configFromEnv,configuredSources}from'../server/config';import{loadSource,isPublicAddress,resolvePublicHost}from'../server/sources';import{sourceSchema}from'../shared/contracts';import{MAX_BYTES}from'../server/errors';import{ics,BASE,CONFIG,SOURCE,SID,HEAD,FakeGoogle}from'./fixtures';
async function temporary(run:(root:string)=>Promise<void>){const root=await fs.mkdtemp(path.join(os.tmpdir(),'ics-ts-test-'));try{await run(root);}finally{await fs.rm(root,{recursive:true,force:true});}}
async function uploaded(){const config={...CONFIG,sources:[SOURCE]},runtime=new Runtime(config,{google:new FakeGoogle()}),{app}=createApp(config,runtime);const form=new FormData();form.append('file',new File([ics([BASE])],'synthetic.ics',{type:'text/calendar'}));expect((await app.request('/api/sources/'+SID+'/upload',{method:'POST',headers:HEAD,body:form})).status).toBe(200);return {app,runtime};}
describe('API integration without TCP or Google',()=>{
 it('enforces auth while health remains public',async()=>{const {app}=createApp(CONFIG);expect((await app.request('/healthz')).status).toBe(200);expect((await app.request('/api/state')).status).toBe(401);expect((await app.request('/api/state',{headers:HEAD})).status).toBe(200);const locked=createApp({...CONFIG,adminToken:''}).app;expect((await locked.request('/api/state',{headers:HEAD})).status).toBe(503);});
 it('uploads, previews anonymously, and blocks Google writes',async()=>{const {app,runtime}=await uploaded();const response=await app.request('/api/sources/'+SID+'/preview',{method:'POST',headers:HEAD});expect(response.status).toBe(200);expect(await response.text()).not.toMatch(/PRIVATE|synthetic-uid/);expect((await app.request('/api/sources/'+SID+'/sync',{method:'POST',headers:HEAD})).status).toBe(400);expect((runtime.google as FakeGoogle).calls).toEqual([]);await runtime.close();expect(runtime.uploads.size).toBe(0);});
 it('invalid upload leaves previous valid source intact',async()=>{const {app,runtime}=await uploaded();const invalid=new FormData();invalid.append('file',new File(['PRIVATE malformed'],'synthetic.ics'));const r=await app.request('/api/sources/'+SID+'/upload',{method:'POST',headers:HEAD,body:invalid});expect(r.status).toBe(400);expect(await r.text()).not.toContain('PRIVATE');expect((await runtime.execute(SID) as any).stats.upserts).toBe(1);});
 it('redacts configured URLs and refuses invalid config without input echo',async()=>{const source=sourceSchema.parse({...SOURCE,kind:'url',location:'https://synthetic.invalid/?secret=PRIVATE'});const {app}=createApp({...CONFIG,sources:[source]});for(const endpoint of ['state','env-export']){const text=await (await app.request('/api/'+endpoint,{headers:HEAD})).text();expect(text).not.toContain('PRIVATE');}const r=await app.request('/api/sources',{method:'POST',headers:{...HEAD,'Content-Type':'application/json'},body:JSON.stringify({name:'PRIVATE',kind:'bad'})});expect(r.status).toBe(400);expect(await r.text()).not.toContain('PRIVATE');});
 it('adds stable source IDs, edits rules and exports them',async()=>{const {app}=createApp({...CONFIG,sources:[]});const created=await app.request('/api/sources',{method:'POST',headers:{...HEAD,'Content-Type':'application/json'},body:JSON.stringify({name:'Synthetic',kind:'upload'})});expect(created.status).toBe(201);const source=await created.json() as any;expect(source.id).toMatch(/^[0-9a-f-]{36}$/);const update=await app.request('/api/sources/'+source.id,{method:'PUT',headers:{...HEAD,'Content-Type':'application/json'},body:JSON.stringify({...source,rules:{excludeRegex:'meeting'}})});expect(update.status).toBe(200);const result=await (await app.request('/api/env-export',{headers:HEAD})).json() as any;expect(result.SOURCES_JSON).toContain(source.id);expect(result.SOURCES_JSON).toContain('meeting');});
 it('rejects over-limit requests and sets privacy response headers',async()=>{const {app}=createApp(CONFIG);const oversized=await app.request('/api/sources',{method:'POST',headers:{...HEAD,'Content-Length':String(MAX_BYTES+100000)},body:'x'});expect(oversized.status).toBe(413);const r=await app.request('/api/state',{headers:HEAD});expect(r.headers.get('cache-control')).toBe('no-store');expect(r.headers.get('referrer-policy')).toBe('no-referrer');});
});
describe('ENV, filesystem and scheduler',()=>{
 it('requires stable unique UUIDs and valid cron/timezone',()=>{for(const raw of ['{}','null','[{}]',JSON.stringify([SOURCE,SOURCE]),JSON.stringify([{...SOURCE,cron:'invalid'}]),JSON.stringify([{...SOURCE,rules:{floatingTimezone:'Invalid/Zone'}}])])expect(()=>configuredSources(raw)).toThrow();expect(configFromEnv({SOURCES_JSON:JSON.stringify([SOURCE])}).writes).toBe(false);});
 it('refuses duplicate direct/file secret configuration without echo',()=>expect(()=>configFromEnv({APP_ADMIN_TOKEN:'PRIVATE',APP_ADMIN_TOKEN_FILE:'/not-read'})).toThrow('ENV und _FILE'));
 it('reads a file and folder and validates every file before returning a plan',async()=>temporary(async root=>{await fs.writeFile(path.join(root,'a.ics'),ics([BASE]));const source=sourceSchema.parse({...SOURCE,kind:'file',location:'a.ics'});expect((await loadSource(source,root,new Map())).stats.upserts).toBe(1);const folder=sourceSchema.parse({...SOURCE,kind:'folder',location:'.'});expect((await loadSource(folder,root,new Map())).stats.files).toBe(1);await fs.writeFile(path.join(root,'bad.ics'),'PRIVATE invalid');await expect(loadSource(folder,root,new Map())).rejects.toThrow();}));
 it('refuses escape paths and symlinks',async()=>temporary(async root=>{await fs.symlink(path.dirname(root),path.join(root,'outside'));const source=sourceSchema.parse({...SOURCE,kind:'file',location:'../outside.ics'});await expect(loadSource(source,root,new Map())).rejects.toThrow(/WATCH_ROOT/);source.location='outside/file.ics';await expect(loadSource(source,root,new Map())).rejects.toThrow();}));
 it('stops contradictory same UIDs across folder files',async()=>temporary(async root=>{await fs.writeFile(path.join(root,'a.ics'),ics([BASE]));await fs.writeFile(path.join(root,'b.ics'),ics([BASE.replace('T110000','T120000')]));await expect(loadSource(sourceSchema.parse({...SOURCE,kind:'folder',location:'.'}),root,new Map())).rejects.toThrow(/Widersprüchliche/);}));
 it('recreates ENV sources with stable target IDs and no DB/data volume',async()=>temporary(async root=>{await fs.writeFile(path.join(root,'a.ics'),ics([BASE]));const config=configFromEnv({WATCH_ROOT:root,SOURCES_JSON:JSON.stringify([{...SOURCE,kind:'file',location:'a.ics'}])});const first=new Runtime(config),second=new Runtime(config);expect((await first.execute(SID)as any).items[0].key).toBe((await second.execute(SID)as any).items[0].key);await first.close();await second.close();}));
 it('executes changed sources on interval and respects disabled/upload sources',async()=>{let input=ics([BASE]);const loader=vi.fn(async()=>input),config={...CONFIG,sources:[sourceSchema.parse({...SOURCE,kind:'url',enabled:true,intervalSeconds:60,location:'https://synthetic.invalid'})]},runtime=new Runtime(config,{urlLoader:loader});await runtime.tick(0);expect(loader).toHaveBeenCalledTimes(1);await runtime.tick(59999);expect(loader).toHaveBeenCalledTimes(1);input=ics([BASE.replace('PRIVATE synthetic title','Mittagspause')]);await runtime.tick(60000);expect(runtime.statuses[SID].stats?.upserts).toBe(0);expect(runtime.statuses[SID].mode).toBe('preview');runtime.sources[0].enabled=false;await runtime.tick(120000);expect(loader).toHaveBeenCalledTimes(2);await runtime.close();});
 it('honors cron in the chosen timezone instead of interval',async()=>{const loader=vi.fn(async()=>ics([BASE])),config={...CONFIG,sources:[sourceSchema.parse({...SOURCE,kind:'url',enabled:true,cron:'0 9 * * 1-5',cronTimezone:'Europe/Berlin',location:'https://synthetic.invalid'})]},runtime=new Runtime(config,{urlLoader:loader});await runtime.tick(Date.parse('2026-01-02T07:59:00Z'));expect(loader).not.toHaveBeenCalled();await runtime.tick(Date.parse('2026-01-02T08:00:00Z'));expect(loader).toHaveBeenCalledTimes(1);await runtime.tick(Date.parse('2026-01-03T08:00:00Z'));expect(loader).toHaveBeenCalledTimes(1);await runtime.close();});
 it.each(['127.0.0.1','10.1.2.3','172.16.1.2','192.168.1.2','169.254.169.254','::1','::ffff:127.0.0.1','fc00::1','2001:db8::1'])('rejects nonpublic URL address %s',address=>expect(isPublicAddress(address)).toBe(false));
 it('validates DNS once and exposes the exact address to pin',async()=>{const resolver=vi.fn(async()=>[{address:'8.8.8.8',family:4}]) as any;expect((await resolvePublicHost('https://synthetic.invalid/feed',resolver)).address.address).toBe('8.8.8.8');expect(resolver).toHaveBeenCalledTimes(1);await expect(resolvePublicHost('file:///etc/passwd',resolver)).rejects.toThrow();await expect(resolvePublicHost('https://user:password@synthetic.invalid',resolver)).rejects.toThrow();const privateResolver=vi.fn(async()=>[{address:'127.0.0.1',family:4}]) as any;await expect(resolvePublicHost('https://synthetic.invalid',privateResolver)).rejects.toThrow(/Private/);});
});
