import{describe,it,expect,vi}from'vitest';
import{promises as fs}from'node:fs';
import{join}from'node:path';import{tmpdir}from'node:os';
import{FileAuthStore}from'../server/auth-store';import{GoogleClient}from'../server/google';import{configFromEnv}from'../server/config';import{parseOAuthEnv}from'../server/auth-migrate';import{reservePrivateOutput}from'../server/oauth-setup';import{CONFIG}from'./fixtures';
const creds={clientId:'synthetic-client',clientSecret:'synthetic-secret',refreshToken:'synthetic-refresh-old'};
async function temporary(run:(dir:string,file:string)=>Promise<void>){const dir=await fs.realpath(await fs.mkdtemp(join(tmpdir(),'ics-auth-store-test-')));await fs.chmod(dir,0o700);try{await run(dir,join(dir,'auth.json'));}finally{await fs.rm(dir,{recursive:true,force:true});}}
function config(file:string){return configFromEnv({AUTH_FILE:file,GOOGLE_CALENDAR_ID:'synthetic-calendar'});}
function transport(refresh:unknown='omitted'){return vi.fn(async(url:any,_options:RequestInit={})=>String(url).includes('/token')?Response.json({access_token:'synthetic-access',expires_in:3600,...refresh==='omitted'?{}:{refresh_token:refresh}}):Response.json({id:'synthetic-event'}));}
describe('file-backed credentials using only synthetic files/transports',()=>{
 it('creates a protected store and does not overwrite a backup or existing file',async()=>temporary(async(dir,file)=>{const store=new FileAuthStore(file);store.create(creds);expect(store.read()).toEqual(creds);expect((await fs.stat(file)).mode&0o777).toBe(0o600);const before=await fs.readFile(file,'utf8');expect(()=>store.create({...creds,refreshToken:'replacement'})).toThrow();expect(await fs.readFile(file,'utf8')).toBe(before);}));
 it('retains the refresh token when Google does not supply a replacement, including restart',async()=>temporary(async(dir,file)=>{const store=new FileAuthStore(file);store.create(creds);const before=await fs.readFile(file,'utf8'),fetcher=transport();await new GoogleClient(config(file),fetcher).get('synthetic');expect(await fs.readFile(file,'utf8')).toBe(before);await new GoogleClient(config(file),fetcher).get('synthetic');expect(fetcher.mock.calls.filter(([url])=>String(url).includes('/token')).map(([,options])=>(options?.body as URLSearchParams).get('refresh_token'))).toEqual([creds.refreshToken,creds.refreshToken]);expect(store.read().refreshToken).toBe(creds.refreshToken);expect(await fs.readdir(dir)).toEqual(['auth.json']);}));
 it('atomically persists a new refresh token before Calendar access and uses it after restart',async()=>temporary(async(dir,file)=>{new FileAuthStore(file).create(creds);const before=(await fs.stat(file)).ino;const bodies:string[]=[];let grants=0;const fetcher=vi.fn(async(url:any,options:RequestInit={})=>{if(String(url).includes('/token')){bodies.push((options.body as URLSearchParams).get('refresh_token')!);return Response.json({access_token:'synthetic-access',expires_in:3600,...++grants===1?{refresh_token:'synthetic-refresh-new'}:{}});}expect(new FileAuthStore(file).read().refreshToken).toBe('synthetic-refresh-new');return Response.json({id:'synthetic'});});await new GoogleClient(config(file),fetcher).get('synthetic');expect((await fs.stat(file)).ino).not.toBe(before);expect((await fs.stat(file)).mode&0o777).toBe(0o600);await new GoogleClient(config(file),fetcher).get('synthetic');expect(bodies).toEqual(['synthetic-refresh-old','synthetic-refresh-new']);expect(await fs.readdir(dir)).toEqual(['auth.json']);}));
 it('single-flights concurrent token requests',async()=>temporary(async(dir,file)=>{new FileAuthStore(file).create(creds);const fetcher=transport('synthetic-refresh-new'),client=new GoogleClient(config(file),fetcher);await Promise.all([client.get('one'),client.get('two')]);expect(fetcher.mock.calls.filter(([url])=>String(url).includes('/token'))).toHaveLength(1);expect(new FileAuthStore(file).read().refreshToken).toBe('synthetic-refresh-new');}));
 it('rejects empty replacement tokens without changing old credentials or calling Calendar',async()=>temporary(async(dir,file)=>{new FileAuthStore(file).create(creds);for(const value of ['',null,'bad\nvalue']){const fetcher=transport(value);await expect(new GoogleClient(config(file),fetcher).get('synthetic')).rejects.toThrow();expect(fetcher).toHaveBeenCalledTimes(1);expect(new FileAuthStore(file).read()).toEqual(creds);}}));
 it('blocks token refresh before HTTP when another process has the store lock',async()=>temporary(async(dir,file)=>{const store=new FileAuthStore(file);store.create(creds);await fs.writeFile(join(dir,'.auth.json.lock'),'');const fetcher=transport();await expect(new GoogleClient(config(file),fetcher).get('synthetic')).rejects.toThrow(/gesperrt/);expect(fetcher).not.toHaveBeenCalled();expect(store.read()).toEqual(creds);}));
 it('leaves old credentials intact on atomic rename failure and cleans temporary files',async()=>temporary(async(dir,file)=>{const store=new FileAuthStore(file,()=>{throw Error('PRIVATE filesystem error');});store.create(creds);await expect(store.withLock(async(snapshot,persist)=>persist('synthetic-refresh-new'))).rejects.toThrow(/sicher gespeichert/);expect(store.read()).toEqual(creds);expect(await fs.readdir(dir)).toEqual(['auth.json']);}));
 it('fails closed for changed credentials while a refresh is in flight',async()=>temporary(async(dir,file)=>{const store=new FileAuthStore(file);store.create(creds);await expect(store.withLock(async(snapshot,persist)=>{await fs.writeFile(file,JSON.stringify({version:1,...creds,refreshToken:'user-updated'}));persist('synthetic-provider-next');})).rejects.toThrow();expect(store.read().refreshToken).toBe('user-updated');}));
 it('sanitizes malformed files, rejects weak permissions and symlinks',async()=>temporary(async(dir,file)=>{const store=new FileAuthStore(file);store.create(creds);await fs.chmod(file,0o644);expect(()=>store.read()).toThrow(/geschützt/);await fs.chmod(file,0o600);await fs.chmod(dir,0o755);expect(()=>store.read()).toThrow();await fs.chmod(dir,0o700);await fs.writeFile(file,'PRIVATE MALFORMED JSON');expect(()=>store.read()).toThrow(/OAuth-Dateispeicher/);await fs.rm(file);await fs.writeFile(join(dir,'original'),JSON.stringify({version:1,...creds}));await fs.symlink(join(dir,'original'),file);expect(()=>store.read()).toThrow();}));
 it('refuses ambiguous auth-file and ENV configurations',async()=>temporary(async(dir,file)=>{new FileAuthStore(file).create(creds);expect(config(file).refreshToken).toBe(creds.refreshToken);expect(()=>configFromEnv({AUTH_FILE:file,GOOGLE_REFRESH_TOKEN:'synthetic'})).toThrow(/nicht.*mischen/);expect(()=>configFromEnv({AUTH_FILE:file,GOOGLE_CLIENT_SECRET_FILE:'/not-read'})).toThrow();}));
 it('parses a helper-produced synthetic backup without evaluating input',()=>{expect(parseOAuthEnv("GOOGLE_CLIENT_ID='synthetic-client'\nGOOGLE_CLIENT_SECRET='synthetic-secret'\nGOOGLE_REFRESH_TOKEN='synthetic-refresh-old'\n")).toEqual(creds);for(const input of ["GOOGLE_CLIENT_ID=$(command)","GOOGLE_CLIENT_ID='one'\nGOOGLE_CLIENT_ID='two'",'UNKNOWN=PRIVATE'])expect(()=>parseOAuthEnv(input)).toThrow();});
 it('future OAuth setup writes JSON directly and atomically replaces it without creating a dotenv',async()=>temporary(async(dir,file)=>{const initial=await reservePrivateOutput(file);await initial.save({clientId:creds.clientId,clientSecret:creds.clientSecret},creds.refreshToken);expect(new FileAuthStore(file).read()).toEqual(creds);const before=(await fs.stat(file)).ino;const replacement=await reservePrivateOutput(file);await replacement.save({clientId:creds.clientId,clientSecret:creds.clientSecret},'synthetic-reauthorized');expect(new FileAuthStore(file).read().refreshToken).toBe('synthetic-reauthorized');expect((await fs.stat(file)).ino).not.toBe(before);expect(await fs.readdir(dir)).toEqual(['auth.json']);}));
});
