import {describe,it,expect,vi} from 'vitest';
import {mkdtemp,writeFile,rm} from 'node:fs/promises';import path from 'node:path';import os from 'node:os';
import {GoogleClient,CalendarListPermissionError,CALENDAR_LIST_SCOPE,type GooglePort} from '../server/google';
import {Runtime} from '../server/runtime';import {createApp} from '../server/app';import {exportConfiguration} from '../server/env-export';import {configFromEnv} from '../server/config';import {sourceSchema} from '../shared/contracts';
import {OAuthSession,CALENDAR_SCOPE} from '../server/oauth-setup';
import {SOURCE,SID,CONFIG,HEAD,ics,BASE,MASTER,EX,FakeGoogle} from './fixtures';
const calendars=[{id:'A',summary:'Writable A',accessRole:'owner' as const,primary:true,writable:true},{id:'B',summary:'Writable B',accessRole:'writer' as const,primary:false,writable:true},{id:'R',summary:'Read only',accessRole:'reader' as const,primary:false,writable:false}];
function google(){const ports=new Map<string,FakeGoogle>();const g:GooglePort={...new FakeGoogle(),get:async()=>null,instances:async()=>[],write:async()=>null,listCalendars:async()=>calendars,forCalendar:id=>{if(!ports.has(id))ports.set(id,new FakeGoogle());return ports.get(id)!;}};return {g,ports};}
function config(){return {...CONFIG,clientId:'synthetic',clientSecret:'synthetic',refreshToken:'synthetic',calendarId:'A',writes:true,sources:[SOURCE]};}
describe('per-source targets and calendar discovery',()=>{
 it('loads every page with minimal fields, including hidden and readonly calendars',async()=>{const transport=vi.fn(async(url:any)=>{const u=new URL(String(url));if(u.pathname.endsWith('/token'))return Response.json({access_token:'synthetic',expires_in:3600});expect(u.pathname).toBe('/calendar/v3/users/me/calendarList');expect(u.searchParams.get('showHidden')).toBe('true');expect(u.searchParams.get('fields')).toBe('items(id,summary,accessRole,primary),nextPageToken');return Response.json(u.searchParams.has('pageToken')?{items:[{...calendars[2],description:'PRIVATE'}]}:{items:calendars.slice(0,2),nextPageToken:'second'});});const client=new GoogleClient(config(),transport);expect(await client.listCalendars()).toEqual(calendars);expect(transport).toHaveBeenCalledTimes(3);});
 it('reports scope failure once without disclosing remote details',async()=>{const transport=vi.fn(async(url:any)=>String(url).includes('/token')?Response.json({access_token:'synthetic',expires_in:3600}):new Response('PRIVATE',{status:403}));await expect(new GoogleClient(config(),transport).listCalendars()).rejects.toBeInstanceOf(CalendarListPermissionError);expect(transport).toHaveBeenCalledTimes(2);});
 it('bounds malformed repeating pagination without partial list',async()=>{const transport=vi.fn(async(url:any)=>String(url).includes('/token')?Response.json({access_token:'synthetic',expires_in:3600}):Response.json({items:[],nextPageToken:'repeat'}));await expect(new GoogleClient(config(),transport).listCalendars()).rejects.toThrow('Paginierung');expect(transport).toHaveBeenCalledTimes(3);});
 it('authenticates calendar listing and returns an actionable scope error',async()=>{const c=config(),{g}=google();g.listCalendars=async()=>{throw new CalendarListPermissionError();};const app=createApp(c,new Runtime(c,{google:g})).app;expect((await app.request('/api/calendars')).status).toBe(401);const response=await app.request('/api/calendars',{headers:HEAD});expect(response.status).toBe(403);expect(await response.json()).toMatchObject({code:'calendar_list_permission_required',requiredScope:CALENDAR_LIST_SCOPE});});
 it('rejects readonly, missing and unauthorized target changes server-side',async()=>{const c=config(),{g}=google(),runtime=new Runtime(c,{google:g}),app=createApp(c,runtime).app;for(const id of ['R','missing']){const res=await app.request('/api/sources/'+SID,{method:'PUT',headers:HEAD,body:JSON.stringify({...SOURCE,calendarId:id})});expect(res.status).toBe(400);expect(runtime.sources[0].calendarId).toBeUndefined();}g.listCalendars=async()=>{throw new CalendarListPermissionError();};expect((await app.request('/api/sources/'+SID,{method:'PUT',headers:HEAD,body:JSON.stringify({...SOURCE,calendarId:'B'})})).status).toBe(403);expect(runtime.sources[0].calendarId).toBeUndefined();});
 it('selects and exports a target for each source type, and a separate global default',async()=>{const c=config(),{g}=google(),runtime=new Runtime({...c,sources:[]},{google:g}),app=createApp(runtime.config,runtime).app;for(const kind of ['upload','file','folder','url']){const res=await app.request('/api/sources',{method:'POST',headers:HEAD,body:JSON.stringify({name:kind,kind,location:kind==='url'?'https://synthetic.invalid/?token=PRIVATE':'.',calendarId:'B'})});expect(res.status).toBe(201);}const res=await app.request('/api/default-calendar',{method:'PUT',headers:HEAD,body:JSON.stringify({calendarId:'B'})});expect(res.status).toBe(200);const data=await(await app.request('/api/env-export',{headers:HEAD})).json() as any;expect(JSON.parse(data.SOURCES_JSON).every((s:any)=>s.calendarId==='B')).toBe(true);expect(data.env).toContain("GOOGLE_CALENDAR_ID='B'");expect(data.env).not.toContain('PRIVATE');});
 it('routes every source kind to its own calendar, preserves old events on target switch and reuses IDs on return',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'ics-target-test-'));try{await writeFile(path.join(root,'a.ics'),ics([BASE]));const c={...config(),watchRoot:root,sources:[sourceSchema.parse({...SOURCE,calendarId:'A'})]}, {g,ports}=google(),runtime=new Runtime(c,{google:g,urlLoader:async()=>ics([BASE])});runtime.uploads.set(SID,ics([BASE]));for(const kind of ['upload','file','folder','url'] as const){runtime.sources[0].kind=kind;runtime.sources[0].location=kind==='file'?'a.ics':kind==='folder'?'.':'https://synthetic.invalid';await runtime.execute(SID,true);expect(ports.get('A')?.events.size).toBe(1);}const old=structuredClone([...ports.get('A')!.events]);runtime.sources[0].calendarId='B';await runtime.execute(SID,true);expect([...ports.get('A')!.events]).toEqual(old);expect([...ports.get('B')!.events.keys()][0]).not.toBe(old[0][0]);runtime.sources[0].calendarId='A';await runtime.execute(SID,true);expect(ports.get('A')!.events.size).toBe(1);await runtime.close();}finally{await rm(root,{recursive:true,force:true});}});
 it('uses global fallback, per-source override and source+calendar ownership markers',async()=>{const c=config(),{g,ports}=google(),runtime=new Runtime(c,{google:g});runtime.uploads.set(SID,ics([MASTER,EX]));await runtime.execute(SID,true);const master=[...ports.get('A')!.events.values()].find(e=>!e.recurringEventId)!;expect(master.extendedProperties?.private).toMatchObject({source:SID,calendar:'A'});runtime.sources[0].calendarId='B';await runtime.execute(SID,true);expect(ports.get('B')!.events.size).toBe(2);expect(ports.get('A')!.events.size).toBe(2);});
 it('blocks sync with no scope or readonly role before any event request/write',async()=>{const c=config(),{g,ports}=google(),runtime=new Runtime(c,{google:g});runtime.uploads.set(SID,ics([BASE]));runtime.sources[0].calendarId='R';await expect(runtime.execute(SID,true)).rejects.toThrow('schreibgeschützt');expect(ports.size).toBe(0);runtime.sources[0].calendarId='A';g.listCalendars=async()=>{throw new CalendarListPermissionError();};await expect(runtime.execute(SID,true)).rejects.toThrow('Kalenderliste');expect(ports.size).toBe(0);});
 it('keeps source+calendar identity stable through restart and export/import',async()=>{const c=config(),a=new Runtime(c);a.uploads.set(SID,ics([BASE]));const p=await a.execute(SID) as any;const out=exportConfiguration(a.sources,c.calendarId);const b=new Runtime(configFromEnv({SOURCES_JSON:out.SOURCES_JSON,GOOGLE_CALENDAR_ID:'A'}));b.uploads.set(SID,ics([BASE]));expect((await b.execute(SID) as any).items[0].key).toBe(p.items[0].key);expect(configFromEnv({SOURCES_JSON:out.SOURCES_JSON}).writes).toBe(false);});
 it('keeps event operations bound to selected calendar, sharing one refreshed token',async()=>{const calls:string[]=[];const transport=vi.fn(async(url:any)=>{calls.push(String(url));return Response.json(String(url).includes('/token')?{access_token:'synthetic',expires_in:3600}:{id:'x'});});const client=new GoogleClient(config(),transport);await client.forCalendar('B@example.invalid').get('x');await client.forCalendar('A').write('POST',undefined,{id:'x'});expect(new URL(calls[1]).pathname).toContain('/calendars/B%40example.invalid/events/x');expect(new URL(calls[2]).pathname).toContain('/calendars/A/events');expect(calls.filter(s=>s.includes('/token'))).toHaveLength(1);});
 it('exports only non-secret configuration and quotes interpolation, apostrophes and JSON backslashes',()=>{const source=sourceSchema.parse({...SOURCE,name:"O'Brien $HOME ${TOKEN} \\ ",calendarId:'B',rules:{excludeRegex:"^O'Brien\\s+$"}});const data=exportConfiguration([source],'A');expect(data.env).toContain("O\\'Brien");expect(data.env).toContain('${TOKEN}');expect(data.env).not.toMatch(/APP_ADMIN_TOKEN|GOOGLE_CLIENT_SECRET|GOOGLE_REFRESH_TOKEN|AUTH_FILE|ENABLE_GOOGLE_WRITES/);expect(JSON.parse(data.SOURCES_JSON)[0]).toMatchObject(source);});
 it('only requests additional calendar-list scope with explicit option and validates both granted scopes',async()=>{const session=new OAuthSession({clientId:'synthetic',clientSecret:'synthetic'},'http://127.0.0.1:45678/',Date.now(),true);expect(new URL(session.authorizationURL()).searchParams.get('scope')).toBe(CALENDAR_SCOPE+' '+CALENDAR_LIST_SCOPE);const reply=session.accept('GET','127.0.0.1:45678','/?state='+session.state+'&code=synthetic');expect(reply.status).toBe(200);await expect(session.exchange('synthetic',vi.fn(async()=>Response.json({scope:CALENDAR_SCOPE,token_type:'Bearer',refresh_token:'synthetic'})))).rejects.toThrow();});
});
