import {it,expect,vi} from 'vitest';
import {sameManagedEvent} from '../server/event-equivalence';import {stampFingerprint} from '../server/event-fingerprint';import {SourcePlanCache} from '../server/source-plan-cache';
import {parseCalendar} from '../server/calendar';import {syncPlan,GoogleClient,type RemoteEvent} from '../server/google';import {Runtime,type RunLog} from '../server/runtime';import {GoogleRequestError} from '../server/google-request-error';import {GoogleWriteUncertainError} from '../server/google-rate-limit';
import {sourceSchema} from '../shared/contracts';import {BASE,MASTER,EX,SID,SOURCE,CONFIG,FakeGoogle,ics} from './fixtures';
function event(){return parseCalendar(ics([BASE]),SID).items[0].event!;}
function remote(desired=event()):RemoteEvent{return {id:desired.extendedProperties.private.key,etag:'synthetic-etag',...structuredClone(desired)};}
function port(){const g=new FakeGoogle();return Object.assign(g,{listCalendars:async()=>['synthetic-target','synthetic-input'].map(id=>({id,summary:'Synthetic',accessRole:'owner' as const,writable:true,primary:false})),listManagedEvents:vi.fn(async()=>structuredClone([...g.events.values()])),forCalendar:()=>g});}
function config(kind:'url'|'google'='url',intervalSeconds=60){return {...CONFIG,writes:true,clientId:'synthetic-client',clientSecret:'synthetic-secret',refreshToken:'synthetic-token',calendarId:'synthetic-target',sources:[sourceSchema.parse({...SOURCE,kind,enabled:true,intervalSeconds,location:'https://synthetic.invalid',sourceCalendarId:kind==='google'?'synthetic-input':undefined})]};}
const pair=()=>ics([BASE,BASE.replace('UID:synthetic-uid','UID:second')]);
it('normalizes equivalent offsets, empty locations and optional single-event timezone',()=>{const desired=event(),current=remote(desired);current.start={dateTime:new Date(desired.start.dateTime!).toISOString()} as any;current.end={dateTime:new Date(desired.end.dateTime!).toISOString()} as any;current.location='';delete current.transparency;expect(sameManagedEvent(current,desired)).toBe(true);});
it('detects every managed privacy/value drift rather than trusting a matching hash',()=>{const desired=event();for(const change of [{summary:'drift'},{location:'old private location'},{visibility:'default'},{transparency:'transparent'},{status:'cancelled'},{description:'synthetic private note'},{attendees:[{responseStatus:'accepted'}]},{attachments:[{mimeType:'text/plain'}]},{conferenceData:{entryPoints:[{}]}},{reminders:{useDefault:true}},{reminders:{useDefault:false,overrides:[{method:'popup',minutes:10}]}}])expect(sameManagedEvent({...remote(desired),...change},desired)).toBe(false);});
it('normalizes RRULE/default order but not genuine recurrence, timezone or exclusive-date change',()=>{const desired=parseCalendar(ics([MASTER]),SID).items[0].event!,current=remote(desired);current.recurrence=['RRULE:WKST=MO;BYDAY=MO;INTERVAL=1;COUNT=4;FREQ=WEEKLY'];expect(sameManagedEvent(current,desired)).toBe(true);current.recurrence=['RRULE:FREQ=WEEKLY;COUNT=3;BYDAY=MO'];expect(sameManagedEvent(current,desired)).toBe(false);current.recurrence=desired.recurrence;current.start={...current.start!,timeZone:'Europe/London'} as any;expect(sameManagedEvent(current,desired)).toBe(false);const day={...desired,start:{date:'2026-03-23'},end:{date:'2026-03-24'},recurrence:undefined} as any;expect(sameManagedEvent(remote(day),day)).toBe(true);expect(sameManagedEvent({...remote(day),end:{date:'2026-03-25'}},day)).toBe(false);});
it('does not rewrite old identical copies solely to add hash metadata',()=>{const desired=event(),current=remote(desired);delete current.extendedProperties!.private!.desiredHash;delete current.extendedProperties!.private!.mappingHash;delete current.extendedProperties!.private!.hashVersion;expect(sameManagedEvent(current,desired)).toBe(true);current.summary='manual drift';current.extendedProperties!.private!.desiredHash=desired.extendedProperties.private.desiredHash!;expect(sameManagedEvent(current,desired)).toBe(false);});
it('fingerprints are normalized after mapping and version/config aware',()=>{const first=event(),second=structuredClone(first);second.start={...second.start,dateTime:new Date(second.start.dateTime!).toISOString()} as any;stampFingerprint(second,SOURCE.rules);expect(second.extendedProperties.private.desiredHash).toBe(first.extendedProperties.private.desiredHash);stampFingerprint(second,{...SOURCE.rules,includeLocation:true});expect(second.extendedProperties.private.mappingHash).not.toBe(first.extendedProperties.private.mappingHash);expect(second.extendedProperties.private.desiredHash).not.toBe(first.extendedProperties.private.desiredHash);});
it('ICS parse cache clones plans and includes content, mapping and destination',()=>{const c=new SourcePlanCache(),data=ics([BASE]),first=c.parse(data,SOURCE,'A');first.items[0].event!.summary='tampered';expect(c.parse(data,SOURCE,'A').items[0].event!.summary).toBe('Termin');expect(c.parse(data,{...SOURCE,rules:{...SOURCE.rules,transforms:[{field:'title',pattern:'PRIVATE',flags:'iu',replacement:'Mapped'}]}},'A').items[0].event!.summary).toBe('Mapped synthetic title');expect(c.parse(ics([BASE.replace('SUMMARY:PRIVATE synthetic title','SUMMARY:Mittagspause')]),SOURCE,'A').items[0].cancel).toBe(true);expect(c.parse(data,SOURCE,'B').items[0].key).not.toBe(c.parse(data,SOURCE,'A').items[0].key);});
it('second identical recurring run has zero writes and uses complete managed snapshot',async()=>{const p=parseCalendar(ics([MASTER,EX]),SID),g=new FakeGoogle();await syncPlan(p,SOURCE,g);g.calls=[];const get=vi.spyOn(g,'get'),instances=vi.spyOn(g,'instances');const result=await syncPlan(p,SOURCE,g,{knownState:structuredClone([...g.events.values()])});expect(result.unchanged).toBe(2);expect(g.calls).toEqual([]);expect(get).not.toHaveBeenCalled();expect(instances).not.toHaveBeenCalled();});
it('does not skip missing destinations or changed location/privacy fields',async()=>{const p=parseCalendar(ics([BASE]),SID),g=new FakeGoogle();await syncPlan(p,SOURCE,g);g.events.get(p.items[0].key)!.location='old location';g.calls=[];await syncPlan(p,SOURCE,g,{knownState:[...g.events.values()]});expect(g.calls).toHaveLength(1);expect(g.calls[0].body.location).toBe('');g.events.clear();g.calls=[];await syncPlan(p,SOURCE,g,{knownState:[]});expect(g.calls[0].method).toBe('POST');});
it('refreshes changing cached ownership before mutation and preserves full preflight',async()=>{const p=parseCalendar(ics([BASE]),SID),g=new FakeGoogle();await syncPlan(p,SOURCE,g);const snapshot=structuredClone([...g.events.values()]);snapshot[0].summary='stale';g.events.get(p.items[0].key)!.extendedProperties={private:{source:'foreign'}};g.calls=[];await expect(syncPlan(p,SOURCE,g,{knownState:snapshot})).rejects.toThrow('gehört');expect(g.calls).toEqual([]);});
it('fresh instance lookup is required after parent update',async()=>{const p=parseCalendar(ics([MASTER,EX]),SID),g=new FakeGoogle();await syncPlan(p,SOURCE,g);const snapshot=structuredClone([...g.events.values()]);g.calls=[];p.items[0].event!.summary='Mapped';const instances=vi.spyOn(g,'instances');await syncPlan(p,SOURCE,g,{knownState:snapshot});expect(instances).toHaveBeenCalled();expect(g.calls[0].method).toBe('PATCH');});
it('already cancelled masters and explicit exceptions are no-ops',async()=>{const g=new FakeGoogle(),p=parseCalendar(ics([MASTER,EX]),SID);await syncPlan(p,SOURCE,g);const cancel=parseCalendar(ics([MASTER,'UID:synthetic-uid\r\nRECURRENCE-ID:20260330T080000Z\r\nSTATUS:CANCELLED']),SID);await syncPlan(cancel,SOURCE,g);g.calls=[];await syncPlan(cancel,SOURCE,g,{knownState:[...g.events.values()]});expect(g.calls).toEqual([]);const onlyCancel=parseCalendar(ics([BASE.replace('BUSYSTATUS:BUSY','BUSYSTATUS:FREE')]),SID);await syncPlan(onlyCancel,SOURCE,g);g.calls=[];await syncPlan(onlyCancel,SOURCE,g,{knownState:[...g.events.values()]});expect(g.calls).toEqual([]);});
it('preserves stable IDs and skips first success after quota; resumes at ten minutes',async()=>{let now=0,limited=true;const g=port(),original=g.write.bind(g);g.write=async(...args)=>{if(limited&&g.calls.length===1){const e=new GoogleRequestError(403,'events.insert','POST','rateLimitExceeded','quota');e.retryAt=now+600000;throw e;}return original(...args);};const logs:RunLog[]=[],loader=vi.fn(async()=>pair()),r=new Runtime(config('url',7200),{google:g,urlLoader:loader,now:()=>now,logger:e=>logs.push(e)});await r.tick();expect(g.calls).toHaveLength(1);expect(r.statuses[SID].progress?.written).toBe(1);for(let i=0;i<20;i++)await r.requestAutomatic(SID,'schedule');expect(loader).toHaveBeenCalledTimes(1);now=599999;await r.tick();expect(loader).toHaveBeenCalledTimes(1);limited=false;now=600000;await r.tick();expect(g.calls).toHaveLength(2);expect(g.events.size).toBe(2);expect(r.statuses[SID].sync?.unchanged).toBe(1);expect(logs.find(e=>e.event==='sync-resume')?.confirmedEarlier).toBe(1);expect(JSON.stringify(logs)).not.toMatch(/PRIVATE|synthetic-uid|synthetic\.invalid|synthetic-target|synthetic-input/);await r.close();});
it('replans changed source after partial success instead of trusting old completed keys',async()=>{let now=0,limited=true,data=pair();const g=port(),original=g.write.bind(g);g.write=async(...args)=>{if(limited&&g.calls.length===1){const e=new GoogleRequestError(403,'events.insert','POST','rateLimitExceeded','quota');e.retryAt=600000;throw e;}return original(...args);};const logs:RunLog[]=[],r=new Runtime(config(),{google:g,urlLoader:async()=>data,now:()=>now,logger:e=>logs.push(e)});await r.tick();data=ics([BASE.replace('20260323T100000','20260323T120000').replace('20260323T110000','20260323T130000'),BASE.replace('UID:synthetic-uid','UID:second')]);limited=false;now=600000;await r.tick();expect(g.calls).toHaveLength(3);expect(logs.some(e=>e.event==='sync-replanned')).toBe(true);await r.close();});
it('restart reconstructs confirmed writes and uncertain committed outcomes from actual targets',async()=>{const g=port(),original=g.write.bind(g);let ambiguous=true;g.write=async(...args)=>{const value=await original(...args);if(ambiguous){ambiguous=false;throw new GoogleWriteUncertainError();}return value;};const c=config(),first=new Runtime(c,{google:g,urlLoader:async()=>ics([BASE]),logger:()=>{}});await expect(first.execute(SID,true)).rejects.toThrow('unbestätigt');expect(g.calls).toHaveLength(1);await first.close();const second=new Runtime(c,{google:g,urlLoader:async()=>ics([BASE]),logger:()=>{}});const result=await second.execute(SID,true) as any;expect(result.unchanged).toBe(1);expect(g.calls).toHaveLength(1);await second.close();});
it('configuration changes invalidate recovery and actual drift is still repaired',async()=>{const g=port(),r=new Runtime(config(),{google:g,urlLoader:async()=>ics([BASE]),logger:()=>{}});await r.execute(SID,true);r.sources[0].rules.transforms=[{field:'title',pattern:'PRIVATE',flags:'iu',replacement:'Mapped'}];r.resetDue(SID);await r.execute(SID,true);expect(g.calls).toHaveLength(2);expect(g.calls[1].body.summary).toBe('Mapped synthetic title');g.events.values().next().value!.summary='manual change';await r.execute(SID,true);expect(g.calls).toHaveLength(3);await r.close();});
it('completion-based cadence prevents immediate catch-up after long run and coalesces requests',async()=>{let now=0,release!:()=>void;const loader=vi.fn(async()=>{await new Promise<void>(resolve=>release=resolve);return ics([BASE]);});const r=new Runtime({...config(),writes:false},{google:port(),urlLoader:loader,now:()=>now,logger:()=>{}});const one=r.requestAutomatic(SID,'schedule'),two=r.requestAutomatic(SID,'schedule');expect(one).toBe(two);await vi.waitFor(()=>expect(loader).toHaveBeenCalledTimes(1));now=120000;release();await one;await Promise.resolve();await r.tick();expect(loader).toHaveBeenCalledTimes(1);now=179999;await r.tick();expect(loader).toHaveBeenCalledTimes(1);await r.close();});
it('permanent400 has no automatic retry until explicit config action',async()=>{let now=0;const g=port(),original=g.write.bind(g),attempt=vi.fn(async()=>{throw new GoogleRequestError(400,'events.insert','POST','badRequest','event_time');});g.write=attempt;const r=new Runtime(config(),{google:g,urlLoader:async()=>ics([BASE]),now:()=>now,logger:()=>{}});await r.tick();expect(r.statuses[SID].automaticPaused).toBe(true);now=3600000;await r.tick();expect(attempt).toHaveBeenCalledTimes(1);g.write=original;r.sources[0].rules.includeLocation=true;r.resetDue(SID);await r.tick();expect(g.calls).toHaveLength(1);await r.close();});
it('uses Google syncToken while still reading actual owned targets on unchanged source',async()=>{const g=port();let reads=0;const record={id:'source-event',etag:'source-etag',summary:'PRIVATE source',start:{dateTime:'2026-03-23T08:00:00Z',timeZone:'UTC'},end:{dateTime:'2026-03-23T09:00:00Z',timeZone:'UTC'}};const readEvents=vi.fn(async(_cal:string,params:Record<string,string>)=>({items:params.syncToken?[]:[record],nextSyncToken:'token-'+(++reads)}));Object.assign(g,{readEvents,listOwnedMasters:async()=>[]});const r=new Runtime(config('google'),{google:g,logger:()=>{}});await r.execute(SID,true);await r.execute(SID,true);expect(readEvents.mock.calls[1][1].syncToken).toBe('token-1');expect(g.listManagedEvents).toHaveBeenCalledTimes(2);expect(g.calls).toHaveLength(1);g.events.values().next().value!.summary='manual drift';await r.execute(SID,true);expect(g.calls).toHaveLength(2);await r.close();});
it('comparison inventory stays filtered/bounded and returns needed managed fields only',async()=>{const calls:URL[]=[],g=new GoogleClient({...CONFIG,clientId:'synthetic',clientSecret:'synthetic',refreshToken:'synthetic'},async(u:any)=>{const request=new URL(String(u));calls.push(request);return request.pathname.endsWith('/token')?Response.json({access_token:'synthetic',expires_in:3600}):Response.json({accessRole:'owner',items:[]});},{requestIntervalMs:0,writeIntervalMs:0});await g.listManagedEvents('synthetic-target',SID,'synthetic-origin');const request=calls[1];expect(request.searchParams.getAll('privateExtendedProperty')).toEqual(['icsSync=v1','source='+SID,'calendar=synthetic-target','origin=synthetic-origin']);expect(request.searchParams.get('showDeleted')).toBe('true');expect(request.searchParams.get('fields')).toContain('summary');expect(request.searchParams.get('fields')).not.toContain('email');expect(request.searchParams.has('timeMin')).toBe(false);g.close();});

it('clears unexpected private fields on recurring metadata PATCH and then skips',async()=>{const plan=parseCalendar(ics([MASTER]),SID),g=new FakeGoogle(),desired=plan.items[0].event!;g.events.set(plan.items[0].key,{...remote(desired),description:'unexpected',attendees:[{}],attachments:[{}],conferenceData:{entryPoints:[{}]}});await syncPlan(plan,SOURCE,g);expect(g.calls[0].method).toBe('PATCH');expect(g.calls[0].body).toMatchObject({description:'',attendees:[],attachments:[],conferenceData:null});const next=await syncPlan(plan,SOURCE,g);expect(next.unchanged).toBe(1);expect(g.calls).toHaveLength(1);});
