import {it,expect,vi} from 'vitest';
import {GoogleRequestError} from '../server/google-request-error';
import {promises as fs} from 'node:fs';import path from 'node:path';import os from 'node:os';
import {parseCalendar} from '../server/calendar';import {clipScope} from '../server/clip-window';import {allowsSnapshotCancellation,validatedWindow} from '../server/snapshot-preview';import {Runtime} from '../server/runtime';import {sourceSchema} from '../shared/contracts';import {DataStore} from '../server/data-store';
import {CONFIG,SOURCE,SID,BASE,ics,FakeGoogle} from './fixtures';
const event=(uid:string,day:string)=>BASE.replace('synthetic-uid',uid).replaceAll('20260323',day);
const clips=(start='20300324T230000Z',end='20300407T220000Z')=>`X-CLIPSTART:${start}\r\nX-CLIPEND:${end}\r\n`;
const bytes=(events:string[],start?:string,end?:string)=>ics(events,clips(start,end));
it('extracts only root UTC clip boundaries, with folding, without inferring event bounds',()=>{const p=parseCalendar(ics([],clips().replace('20300324T230000Z','20300324T\r\n 230000Z')),SID);expect(p.clipWindow).toEqual({start:'2030-03-24T23:00:00.000Z',end:'2030-04-07T22:00:00.000Z'});});
it.each([ 'X-CLIPSTART:20300324T230000Z\r\n',clips()+'X-CLIPSTART:20300324T230000Z\r\n',clips().replace('X-CLIPSTART:','X-CLIPSTART;VALUE=DATE:'),clips().replace('20300324T230000Z','20300324T230000'),clips('20300407T220000Z','20300324T230000Z'),clips().replace('20300324T230000Z','20300231T230000Z')])('rejects missing duplicate reversed ambiguous or invalid root clips',extra=>expect(()=>parseCalendar(ics([],extra),SID)).toThrow());
it('clip mode cannot treat VEVENT clip properties as root authority',()=>{const p=parseCalendar(ics([event('nested','20300325')+'\r\n'+clips().trim()]),SID);expect(()=>clipScope(p,sourceSchema.parse({...SOURCE,kind:'folder',folderMode:'snapshot',snapshotFile:'weekly.ics',snapshotClip:{boundary:'protect-boundary',completeExportConfirmed:true,ordering:'manual-confirm'}}))).toThrow('VCALENDAR');});
it('DST/all-day boundary policy protects series, crossing events and uncertain touching ends',()=>{const scope:any={authority:'window',basis:'clip',boundary:'exclusive',window:{start:'2030-03-24T23:00:00.000Z',end:'2030-03-31T22:00:00.000Z',timezone:'Europe/Berlin'}};const w=validatedWindow(scope)!;expect((w.endMillis-w.startMillis)/3600000).toBe(167);const e:any={id:'synthetic',start:{date:'2030-03-25'},end:{date:'2030-04-01'}};expect(allowsSnapshotCancellation(e,scope)).toBe(true);expect(allowsSnapshotCancellation(e,{...scope,boundary:'protect-boundary'})).toBe(false);expect(allowsSnapshotCancellation({...e,start:{date:'2030-03-24'}},scope)).toBe(false);expect(allowsSnapshotCancellation({...e,recurrence:['RRULE:FREQ=DAILY']},scope)).toBe(false);});
async function fixture(run:(a:any)=>Promise<void>){const root=await fs.mkdtemp(path.join(os.tmpdir(),'synthetic-clip-')),input=path.join(root,'in'),data=path.join(root,'data');await fs.mkdir(input);await fs.mkdir(data,{mode:0o700});const source=sourceSchema.parse({...SOURCE,kind:'folder',location:'.',folderMode:'snapshot',snapshotFile:'weekly.ics',snapshotClip:{completeExportConfirmed:true,boundary:'exclusive',ordering:'manual-confirm'},calendarId:'synthetic-target',enabled:true});const g=Object.assign(new FakeGoogle(),{listCalendars:async()=>[{id:'synthetic-target',summary:'Synthetic',accessRole:'owner' as const,writable:true,primary:false}],listManagedEvents:async()=>structuredClone([...g.events.values()]),forCalendar:()=>g});const config={...CONFIG,clientId:'synthetic',clientSecret:'synthetic',refreshToken:'synthetic',writes:true,watchRoot:input,dataDir:data,calendarId:'synthetic-target',sources:[source]};const make=()=>new Runtime(config,{google:g,logger:()=>{}}),r=make(),file=path.join(input,'weekly.ics');try{await run({r,make,g,file,data,source});}finally{await r.close();await fs.rm(root,{recursive:true,force:true});}}
async function apply(r:Runtime,emptyConfirmed=false,newerConfirmed=true){const p:any=await r.execute(SID);await r.execute(SID,true,undefined,{token:p.snapshotPreview.token,emptyConfirmed,newerConfirmed});return p;}
it('overlapping newest export cancels only its missing inside event, preserves outside and blocks known-old resurrection after restart',()=>fixture(async({r,make,g,file})=>{const old=bytes([event('a','20300325'),event('b','20300329'),event('c','20300403')]);await fs.writeFile(file,old);await apply(r);await fs.writeFile(file,bytes([event('c','20300403')],'20300328T230000Z','20300410T220000Z'));const p=await apply(r);expect(p.snapshotPreview.proposedRemovals).toHaveLength(1);expect([...g.events.values()].filter((e:any)=>e.status==='confirmed')).toHaveLength(2);await r.close();await fs.writeFile(file,old);const restarted=make(),before=g.calls.length;try{await expect(restarted.execute(SID)).rejects.toThrow('Replay');expect(g.calls).toHaveLength(before);}finally{await restarted.close();}}));
it('new byte order and empty completeness confirmations are independent and required',()=>fixture(async({r,g,file})=>{await fs.writeFile(file,bytes([event('a','20300325')]));await expect(apply(r,false,false)).rejects.toThrow('Exportreihenfolge');expect(g.calls).toHaveLength(0);await apply(r);await fs.writeFile(file,bytes([]));await expect(apply(r,false,true)).rejects.toThrow('leer');await apply(r,true,true);expect([...g.events.values()][0].status).toBe('cancelled');}));
it('clips without confirmed complete exporter contract propose no absence cancellations',()=>fixture(async({r,g,file})=>{await fs.writeFile(file,bytes([event('a','20300325')]));await apply(r);r.sources[0].snapshotClip!.completeExportConfirmed=false;await fs.writeFile(file,bytes([]));const p=await apply(r,true);expect(p.snapshotPreview.authority).toBe('unknown');expect(p.snapshotPreview.proposedRemovals).toHaveLength(0);expect([...g.events.values()][0].status).toBe('confirmed');}));
it('partial import remains pending across crash, blocks supersession and resumes same bytes by actual target comparison',()=>fixture(async({r,make,g,file,data})=>{const original=bytes([event('a','20300325'),event('b','20300329')]);await fs.writeFile(file,original);g.failAt=2;await expect(apply(r)).rejects.toThrow();expect((await new DataStore(data).read(SID)).clipHistory!.pending).toBe(true);await r.close();const restarted=make();try{await fs.writeFile(file,bytes([]));await expect(restarted.execute(SID)).rejects.toThrow('unvollständig');await fs.writeFile(file,original);g.failAt=0;const result:any=await restarted.execute(SID,true);expect(result.unchanged).toBe(1);expect((await new DataStore(data).read(SID)).clipHistory!.pending).toBe(false);}finally{await restarted.close();}}));
it('missing clip pair stops before import even with confirmed contract',()=>fixture(async({r,g,file})=>{await fs.writeFile(file,ics([event('a','20300325')]));await expect(r.execute(SID)).rejects.toThrow('VCALENDAR');expect(g.calls).toHaveLength(0);}));

it('clip final refresh drift rejects the changed target before cancellation or cleanup',()=>fixture(async({r,g,file})=>{await fs.writeFile(file,bytes([event('a','20300325')]));await apply(r);await fs.writeFile(file,bytes([]));const p:any=await r.execute(SID),original=g.get.bind(g);g.get=async(id:string)=>{const e=await original(id);return e?{...e,etag:'synthetic-drift',start:{date:'2030-05-01'},end:{date:'2030-05-02'}}:null;};const before=g.calls.length;await expect(r.execute(SID,true,undefined,{token:p.snapshotPreview.token,emptyConfirmed:true,newerConfirmed:true})).rejects.toThrow('Absageziel nach bestätigter');expect(g.calls).toHaveLength(before);expect(await fs.readFile(file)).toEqual(Buffer.from(bytes([])));}));
it('quota failure preserves clip pending approval and resumes only approved bytes after restart',()=>fixture(async({r,make,g,file,data})=>{await fs.writeFile(file,bytes([event('a','20300325'),event('b','20300329')]));const write=g.write.bind(g);let quota=true;g.write=async(...args:Parameters<FakeGoogle['write']>)=>{if(quota&&g.calls.length===1){const e=new GoogleRequestError(403,'events.insert','POST','rateLimitExceeded','synthetic');e.retryAt=Date.now()+600000;throw e;}return write(...args);};await expect(apply(r)).rejects.toThrow('rateLimitExceeded');expect((await new DataStore(data).read(SID)).clipHistory!.pending).toBe(true);await r.close();quota=false;const restarted=make();try{const result:any=await restarted.execute(SID,true);expect(result.unchanged).toBe(1);expect(g.calls).toHaveLength(2);expect((await new DataStore(data).read(SID)).clipHistory!.pending).toBe(false);}finally{await restarted.close();}}));
it('crash after target acknowledgements retains pending ledger and retry compares actual targets',()=>fixture(async({r,make,g,file,data})=>{await fs.writeFile(file,bytes([event('a','20300325')]));const write=DataStore.prototype.write;const spy=vi.spyOn(DataStore.prototype,'write').mockImplementation(async function(this:DataStore,state){if(state.clipHistory&&!state.clipHistory.pending)throw Error('Synthetic checkpoint crash');return write.call(this,state);});await expect(apply(r)).rejects.toThrow();spy.mockRestore();expect((await new DataStore(data).read(SID)).clipHistory!.pending).toBe(true);await r.close();const restarted=make();try{const result:any=await restarted.execute(SID,true);expect(result.unchanged).toBe(1);expect(g.calls).toHaveLength(1);expect((await new DataStore(data).read(SID)).clipHistory!.pending).toBe(false);}finally{await restarted.close();}}));

it('missing clip ledger cannot reuse persisted approval to write or resurrect targets',()=>fixture(async({r,make,g,file,data})=>{await fs.writeFile(file,bytes([event('a','20300325')]));await apply(r);const store=new DataStore(data),state=await store.read(SID);delete state.clipHistory;await store.write(state);await r.close();const restarted=make(),before=g.calls.length;try{await expect(restarted.execute(SID,true)).rejects.toThrow('Clip-Reihenfolge fehlt');expect(g.calls).toHaveLength(before);}finally{await restarted.close();}}));
