import{sourceSchema}from'../shared/contracts';import{demoConfig,DEMO_ID}from'../server/fixtures';import type{GooglePort,RemoteEvent}from'../server/google';import{sameTime}from'../server/google';import type{EventTime}from'../shared/contracts';import{AppError}from'../server/errors';
export const SID=DEMO_ID;export const SOURCE=sourceSchema.parse({id:SID,name:'Synthetic',kind:'upload'});export const CONFIG={...demoConfig(),adminToken:'synthetic-admin',demo:false};export const HEAD={Authorization:'Bearer synthetic-admin'};
export const BASE='UID:synthetic-uid\r\nDTSTART;TZID=Europe/Berlin:20260323T100000\r\nDTEND;TZID=Europe/Berlin:20260323T110000\r\nSUMMARY:PRIVATE synthetic title\r\nTRANSP:OPAQUE\r\nX-MICROSOFT-CDO-BUSYSTATUS:BUSY';
export const MASTER=BASE+'\r\nRRULE:FREQ=WEEKLY;COUNT=4;BYDAY=MO';export const EX='UID:synthetic-uid\r\nRECURRENCE-ID:20260330T080000Z\r\nDTSTART:20260331T120000Z\r\nDTEND:20260331T130000Z';
export function ics(events:string[]=[],extra=''){return new TextEncoder().encode('BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Synthetic tests//EN\r\n'+extra+events.map(e=>'BEGIN:VEVENT\r\n'+e+'\r\nEND:VEVENT\r\n').join('')+'END:VCALENDAR\r\n');}
export class FakeGoogle implements GooglePort {
 events=new Map<string,RemoteEvent>();calls:{method:string;id?:string;body:any;etag?:string}[]=[];failAt=0;missingInstances=false;
 async get(id:string){return structuredClone(this.events.get(id)??null);}
 async instances(parent:string,original:EventTime){if(this.missingInstances)return [];const previous=[...this.events.values()].find(e=>e.recurringEventId===parent&&sameTime(e.originalStartTime,original));if(previous)return [structuredClone(previous)];const e:RemoteEvent={id:parent+'_generated_'+this.events.size,recurringEventId:parent,originalStartTime:original,status:'confirmed',etag:'e1'};this.events.set(e.id,e);return [structuredClone(e)];}
 async write(method:'POST'|'PUT'|'PATCH',id:string|undefined,body:any,etag?:string){this.calls.push({method,id,body:structuredClone(body),etag});if(this.failAt===this.calls.length)throw new AppError('Synthetic API failure');const eid=id??body.id,current=this.events.get(eid);if(method==='POST'&&current)return {id:eid,conflict:true};const e:RemoteEvent={...(method==='PATCH'?current:{}),...body,id:eid,etag:'next',...current?.recurringEventId?{recurringEventId:current.recurringEventId,originalStartTime:current.originalStartTime}:{}};this.events.set(eid,e);return structuredClone(e);}
}
