import {describe,it,expect,vi} from 'vitest';
import {promises as fs} from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {FolderWatchManager,type WatchAdapters} from '../server/folder-watch';
import {Runtime} from '../server/runtime';
import {folderFingerprint,loadSource} from '../server/sources';
import {sourceSchema} from '../shared/contracts';
import {exportConfiguration} from '../server/env-export';
import {SOURCE,CONFIG,SID,ics,BASE} from './fixtures';
const source=sourceSchema.parse({...SOURCE,kind:'folder',location:'.',enabled:true,watch:true});
const flush=async()=>{for(let i=0;i<5;i++)await Promise.resolve();};
function adapter(){let signature='first',identity='inode1';const changes:(()=>void)[]=[],errors:(()=>void)[]=[],close=vi.fn();const adapters:WatchAdapters={fingerprint:vi.fn(async()=>({signature,path:'/synthetic',identity})),watch:vi.fn((_path,change,error)=>{changes.push(change);errors.push(error);return {close};})};return {adapters,changes,errors,close,set:(s:string)=>{signature=s;},replace:()=>{identity='inode2';signature='replaced';}};}
async function temporary(run:(root:string)=>Promise<void>){const root=await fs.mkdtemp(path.join(os.tmpdir(),'ics-watch-test-'));try{await run(root);}finally{await fs.rm(root,{recursive:true,force:true});}}
describe('opt-in folder watch with synthetic adapters',()=>{
 it('is folder-only, defaults off and exports the opt-in setting',()=>{expect(SOURCE.watch).toBe(false);expect(sourceSchema.safeParse({...SOURCE,watch:true}).success).toBe(false);expect(JSON.parse(exportConfiguration([source],'').SOURCES_JSON)[0].watch).toBe(true);});
 it('debounces bursts until the folder snapshot is stable',async()=>{const a=adapter(),run=vi.fn(async()=>{}),m=new FolderWatchManager('/',run,a.adapters);await m.tick([source],0);await m.tick([source],1000);await flush();expect(run).toHaveBeenCalledOnce();a.set('changed');a.changes[0]();a.changes[0]();await m.tick([source],1100);a.set('changed-again');a.changes[0]();await m.tick([source],1800);await m.tick([source],2000);expect(run).toHaveBeenCalledOnce();await m.tick([source],2800);await flush();expect(run).toHaveBeenCalledTimes(2);await m.close();expect(a.close).toHaveBeenCalledOnce();});
 it('polls for missed native events and reconnects after watcher errors',async()=>{const a=adapter(),run=vi.fn(async()=>{}),m=new FolderWatchManager('/',run,a.adapters);await m.tick([source],0);await m.tick([source],1000);await flush();a.set('missed-event');await m.tick([source],6000);await m.tick([source],7000);await flush();expect(run).toHaveBeenCalledTimes(2);a.errors[0]();await m.tick([source],8000);expect(m.statuses[SID].mode).toBe('polling');await m.tick([source],31000);expect(a.adapters.watch).toHaveBeenCalledTimes(2);await m.close();});
 it('uses polling when native watching cannot attach',async()=>{const a=adapter();a.adapters.watch=vi.fn(()=>{throw new Error('synthetic unsupported mount');});const run=vi.fn(async()=>{}),m=new FolderWatchManager('/',run,a.adapters);await m.tick([source],0);await m.tick([source],1000);await flush();expect(run).toHaveBeenCalledOnce();expect(m.statuses[SID].error).toContain('Polling');a.set('new-file');await m.tick([source],6000);await m.tick([source],7000);await flush();expect(run).toHaveBeenCalledTimes(2);await m.close();});
 it('reattaches on directory replacement and closes when disabled',async()=>{const a=adapter(),m=new FolderWatchManager('/',async()=>{},a.adapters);await m.tick([source],0);a.replace();a.changes[0]();await m.tick([source],100);expect(a.close).toHaveBeenCalledOnce();expect(a.adapters.watch).toHaveBeenCalledTimes(2);await m.tick([{...source,enabled:false}],200);expect(a.close).toHaveBeenCalledTimes(2);expect(m.statuses[SID]).toBeUndefined();await m.close();});
 it('never dispatches disabled sources or a path that fails validation',async()=>{const a=adapter(),run=vi.fn(async()=>{}),m=new FolderWatchManager('/',run,a.adapters);await m.tick([{...source,enabled:false}],0);expect(a.adapters.fingerprint).not.toHaveBeenCalled();a.adapters.fingerprint=vi.fn(async()=>{throw new Error('synthetic forbidden symlink');});await m.tick([source],1000);await m.tick([source],6000);expect(run).not.toHaveBeenCalled();expect(a.adapters.watch).not.toHaveBeenCalled();await m.close();});
 it('retries an incomplete-write failure without an unbounded trigger queue',async()=>{const a=adapter(),run=vi.fn().mockRejectedValueOnce(new Error('synthetic incomplete ICS')).mockResolvedValue(undefined),m=new FolderWatchManager('/',run,a.adapters);await m.tick([source],0);await m.tick([source],1000);await flush();await m.tick([source],2000);expect(run).toHaveBeenCalledOnce();await m.tick([source],6000);await flush();expect(run).toHaveBeenCalledTimes(2);await m.close();});
 it('keeps one running dispatch while changes burst and schedules the final stable state',async()=>{const a=adapter();let finish!:()=>void;const run=vi.fn().mockImplementationOnce(()=>new Promise<void>(r=>{finish=r;})).mockResolvedValue(undefined),m=new FolderWatchManager('/',run,a.adapters);await m.tick([source],0);await m.tick([source],1000);a.set('changed');a.changes[0]();await m.tick([source],1500);await m.tick([source],2500);expect(run).toHaveBeenCalledOnce();finish();await flush();await m.tick([source],3500);await flush();expect(run).toHaveBeenCalledTimes(2);await m.close();});
 it('re-establishes watches and stable initial scans after restart',async()=>{const a=adapter(),run=vi.fn(async()=>{});for(let n=0;n<2;n++){const m=new FolderWatchManager('/',run,a.adapters);await m.tick([source],0);await m.tick([source],1000);await flush();await m.close();}expect(run).toHaveBeenCalledTimes(2);expect(a.adapters.watch).toHaveBeenCalledTimes(2);});
});
describe('filesystem watch safety and runtime queue',()=>{
 it('fingerprints add/change/delete/rename/atomic replacement without recursive traversal',async()=>temporary(async root=>{await fs.writeFile(path.join(root,'a.ics'),ics([BASE]));let previous=(await folderFingerprint(root,'.')).signature;for(const action of [async()=>fs.writeFile(path.join(root,'b.ics'),ics([BASE.replace('synthetic-uid','second')])),async()=>fs.rename(path.join(root,'a.ics'),path.join(root,'renamed.ics')),async()=>fs.writeFile(path.join(root,'new.tmp'),ics([BASE])),async()=>fs.rename(path.join(root,'new.tmp'),path.join(root,'renamed.ics')),async()=>fs.rm(path.join(root,'b.ics'))]){await action();const next=(await folderFingerprint(root,'.')).signature;expect(next).not.toBe(previous);previous=next;}await fs.mkdir(path.join(root,'nested'));await fs.writeFile(path.join(root,'nested','ignored.ics'),'invalid');expect((await loadSource(source,root,new Map())).stats.files).toBe(1);}));
 it('rejects symlink escape and partial ICS while deleted files never imply cancellation',async()=>temporary(async root=>{await fs.writeFile(path.join(root,'a.ics'),ics([BASE]));await fs.writeFile(path.join(root,'b.ics'),ics([BASE.replace('synthetic-uid','second')]));expect((await loadSource(source,root,new Map())).stats.upserts).toBe(2);await fs.rm(path.join(root,'b.ics'));expect((await loadSource(source,root,new Map())).stats.explicitCancellations).toBe(0);await fs.writeFile(path.join(root,'a.ics'),'BEGIN:VCALENDAR\r\nBEGIN:VEVENT');await expect(loadSource(source,root,new Map())).rejects.toThrow();await fs.symlink(path.dirname(root),path.join(root,'outside'));await expect(folderFingerprint(root,'outside')).rejects.toThrow(/WATCH_ROOT/);}));
 it('coalesces watch/Cron races and serializes manual runs with one final watched rerun',async()=>{const a=adapter(),runtime=new Runtime({...CONFIG,sources:[source]},{watchAdapters:a.adapters});let release!:()=>void;let active=0,max=0;const execution=vi.spyOn(runtime,'execute').mockImplementation(async()=>{active++;max=Math.max(max,active);await new Promise<void>(r=>{release=r;});active--;return undefined;});const first=runtime.requestAutomatic(SID,'watch');expect(runtime.requestAutomatic(SID,'schedule')).toBe(first);for(let n=0;n<20;n++)expect(runtime.requestAutomatic(SID,'watch')).toBe(first);expect(execution).toHaveBeenCalledOnce();runtime.sources[0].enabled=false;release();await first;await flush();expect(execution).toHaveBeenCalledOnce();expect(max).toBe(1);execution.mockRestore();await runtime.close();});
 it('honors disabled state when queued behind a manual operation',async()=>temporary(async root=>{await fs.writeFile(path.join(root,'a.ics'),ics([BASE]));const runtime=new Runtime({...CONFIG,watchRoot:root,sources:[source]});let finish!:()=>void;const delayed=sourceSchema.parse({...SOURCE,id:crypto.randomUUID(),kind:'url',location:'https://synthetic.invalid'});runtime.sources.push(delayed);const loader=vi.fn(()=>new Promise<Uint8Array>(r=>{finish=()=>r(ics([BASE]));}));(runtime as any).urlLoader=loader;const manual=runtime.execute(delayed.id);await flush();const watched=runtime.requestAutomatic(SID,'watch');runtime.sources[0].enabled=false;finish();await manual;await watched;expect(runtime.statuses[SID]).toBeUndefined();await runtime.close();}));
 it('watch and manual file operations share the serial runtime queue',async()=>temporary(async root=>{await fs.writeFile(path.join(root,'a.ics'),ics([BASE]));const runtime=new Runtime({...CONFIG,watchRoot:root,sources:[source]});const [first,second]=await Promise.all([runtime.execute(SID),runtime.requestAutomatic(SID,'watch')]);expect((first as any).stats.upserts).toBe(1);expect((second as any).stats.upserts).toBe(1);await runtime.close();}));
});

describe('native local folder watcher smoke check',()=>{
 it('attaches a real non-recursive watch and reacts to an atomic file replacement',async()=>temporary(async root=>{await fs.writeFile(path.join(root,'a.ics'),ics([BASE]));const run=vi.fn(async()=>{}),manager=new FolderWatchManager(root,run);try{const now=Date.now();await manager.tick([source],now);await manager.tick([source],now+1000);await flush();expect(manager.statuses[SID].error).toBeUndefined();await fs.writeFile(path.join(root,'replace.tmp'),ics([BASE.replace('T110000','T120000')]));await fs.rename(path.join(root,'replace.tmp'),path.join(root,'a.ics'));await vi.waitFor(async()=>{await manager.tick([source],now+6000);expect(manager.statuses[SID].mode).toBe('settling');});await manager.tick([source],now+7000);await flush();expect(run).toHaveBeenCalledTimes(2);}finally{await manager.close();}}));
});

it('reports the attached watch active for an empty folder even when there is nothing to sync',async()=>{const a=adapter();a.set('empty-folder');const run=vi.fn(async()=>{throw new Error('synthetic no ICS files');}),manager=new FolderWatchManager('/',run,a.adapters);await manager.tick([source],0);await manager.tick([source],1000);await flush();expect(manager.statuses[SID].mode).toBe('watching');await manager.tick([source],6000);await flush();expect(manager.statuses[SID].mode).toBe('watching');await manager.close();});

it('pauses revision failures until bytes/config change and exponentially backs off transient failures',async()=>{const {RevisionError}=await import('../server/errors');const a=adapter(),run=vi.fn().mockRejectedValue(new RevisionError('synthetic approval required')),m=new FolderWatchManager('/',run,a.adapters);await m.tick([source],0);await m.tick([source],1000);await flush();for(let now=6000;now<60000;now+=5000){await m.tick([source],now);await flush();}expect(run).toHaveBeenCalledTimes(1);a.set('next');await m.tick([source],61000);await m.tick([source],62000);await flush();expect(run).toHaveBeenCalledTimes(2);await m.tick([{...source,intervalSeconds:600}],63000);await m.tick([{...source,intervalSeconds:600}],64000);await flush();expect(run).toHaveBeenCalledTimes(3);await m.close();const b=adapter(),transient=vi.fn().mockRejectedValue(new Error('synthetic partial copy')),n=new FolderWatchManager('/',transient,b.adapters);await n.tick([source],0);await n.tick([source],1000);await flush();for(let now=6000;now<=60000;now+=5000){await n.tick([source],now);await flush();}expect(transient.mock.calls.length).toBeLessThan(6);await n.close();});
