import {Runtime} from '../server/runtime';
import {CONFIG} from './fixtures';
import {describe,it,expect,vi} from 'vitest';
import {GoogleSourceReader,googleSourcePlan,ExpiredCursor,safeGoogleSourcePlan,reconcileGoogleMasters,type SourceEvent} from '../server/google-source';
import {sourceSchema} from '../shared/contracts';
import {SID} from './fixtures';
const source=sourceSchema.parse({id:SID,name:'Synthetic',kind:'google',sourceCalendarId:'input'});
const master:SourceEvent={id:'parent',start:{date:'2020-01-01'},end:{date:'2020-01-02'},recurrence:['RRULE:FREQ=YEARLY;COUNT=20']};
const exception:SourceEvent={id:'exception',recurringEventId:'parent',originalStartTime:{date:'2026-01-01'},start:{date:'2026-04-01'},end:{date:'2026-04-02'}};
describe('Google recurring parent hydration',()=>{
 it('resolves a missing old master for a moved exception instead of dropping its native series',async()=>{const getSourceEvent=vi.fn(async()=>master),readEvents=vi.fn(async()=>({items:[exception],nextSyncToken:'t1'})),snapshot=await new GoogleSourceReader().snapshot('input',{readEvents,getSourceEvent});const plan=googleSourcePlan(snapshot.events,source);expect(plan.items).toHaveLength(2);expect(plan.items.some(i=>i.event?.recurrence)).toBe(true);expect(plan.items.find(i=>i.parent)?.event?.start).toEqual(exception.start);expect(getSourceEvent).toHaveBeenCalledWith('input','parent');expect(readEvents.mock.calls).toHaveLength(1);});
 it('retains hydrated masters across later exception-only incremental deltas',async()=>{const getSourceEvent=vi.fn(async()=>master),readEvents=vi.fn().mockResolvedValueOnce({items:[exception],nextSyncToken:'t1'}).mockResolvedValueOnce({items:[{...exception,start:{date:'2026-05-01'},end:{date:'2026-05-02'}}],nextSyncToken:'t2'}),reader=new GoogleSourceReader();await reader.snapshot('input',{readEvents,getSourceEvent});const snapshot=await reader.snapshot('input',{readEvents,getSourceEvent});expect(snapshot.events).toHaveLength(2);expect(getSourceEvent).toHaveBeenCalledOnce();expect(readEvents.mock.calls[1][1].syncToken).toBe('t1');});
 it('uses a listed/cached master without additional retrieval, including multiple pages',async()=>{const getSourceEvent=vi.fn(async()=>master),readEvents=vi.fn().mockResolvedValueOnce({items:[exception],nextPageToken:'second'}).mockResolvedValueOnce({items:[master],nextSyncToken:'full'}).mockResolvedValueOnce({items:[exception],nextSyncToken:'delta'}),reader=new GoogleSourceReader();await reader.snapshot('input',{readEvents,getSourceEvent});expect((await reader.snapshot('input',{readEvents,getSourceEvent})).events).toHaveLength(2);expect(getSourceEvent).not.toHaveBeenCalled();});
 it('resolves again after a 410 reset with exception-only full results',async()=>{const getSourceEvent=vi.fn(async()=>master),readEvents=vi.fn().mockResolvedValueOnce({items:[master,exception],nextSyncToken:'first'}).mockRejectedValueOnce(new ExpiredCursor()).mockResolvedValueOnce({items:[exception],nextSyncToken:'new'}),reader=new GoogleSourceReader();await reader.snapshot('input',{readEvents,getSourceEvent});const snapshot=await reader.snapshot('input',{readEvents,getSourceEvent});expect(snapshot.events).toHaveLength(2);expect(getSourceEvent).toHaveBeenCalledOnce();expect(readEvents.mock.calls[2][1]).not.toHaveProperty('syncToken');});
 it('cancels a missing deleted parent returned by GET while suppressing stale children',async()=>{const getSourceEvent=vi.fn(async()=>({id:'parent',status:'cancelled'})),readEvents=vi.fn(async()=>({items:[exception],nextSyncToken:'t'}));const snapshot=await new GoogleSourceReader().snapshot('input',{readEvents,getSourceEvent});expect(googleSourcePlan(snapshot.events,source).items).toMatchObject([{cancel:true}]);});
 it('accepts orphan cancellation tombstones only when the parent GET proves absent',async()=>{const getSourceEvent=vi.fn(async()=>null),readEvents=vi.fn(async()=>({items:[{...exception,status:'cancelled'}],nextSyncToken:'t'}));const snapshot=await new GoogleSourceReader().snapshot('input',{readEvents,getSourceEvent});expect(googleSourcePlan(snapshot.events,source).items).toEqual([]);expect(getSourceEvent).toHaveBeenCalledOnce();});
 it('stops on a genuinely missing live parent, inaccessible GET or malformed parent',async()=>{for(const getSourceEvent of [vi.fn(async()=>{throw new Error('synthetic permission failure');}),vi.fn(async()=>({...master,id:'wrong'})),vi.fn(async()=>({...master,recurrence:undefined}))])await expect(new GoogleSourceReader().snapshot('input',{readEvents:async()=>({items:[exception],nextSyncToken:'t'}),getSourceEvent})).rejects.toThrow();});
 it('quarantines truly unavailable live parent IDs explicitly for destination protection',async()=>{const snapshot=await new GoogleSourceReader().snapshot('input',{readEvents:async()=>({items:[exception],nextSyncToken:'t'}),getSourceEvent:async()=>null});expect(snapshot.unresolvedParents).toEqual(['parent']);expect(snapshot.events).toEqual([exception]);});
 it('does not hydrate or produce a plan after partial pagination failure',async()=>{const getSourceEvent=vi.fn(async()=>master),readEvents=vi.fn().mockResolvedValueOnce({items:[exception],nextPageToken:'p'}).mockRejectedValueOnce(new Error('synthetic failure'));await expect(new GoogleSourceReader().snapshot('input',{readEvents,getSourceEvent})).rejects.toThrow();expect(getSourceEvent).not.toHaveBeenCalled();});
});

it('processes healthy events while explicitly quarantining unavailable-parent exceptions',async()=>{const runtime=new Runtime({...CONFIG,sources:[source]},{google:{get:async()=>null,instances:async()=>[],write:async()=>{throw Error('Synthetic writes forbidden');},listCalendars:async()=>[{id:'input',summary:'Synthetic',accessRole:'reader',primary:false,writable:false}],readEvents:async()=>({items:[exception,{id:'healthy',start:{date:'2026-04-03'},end:{date:'2026-04-04'}}],nextSyncToken:'t'}),getSourceEvent:async()=>null}});const plan=await runtime.execute(source.id) as any;expect(plan.items).toHaveLength(1);expect(plan.stats.quarantinedSeries).toBe(1);expect(plan.warnings.join(' ')).toContain('zurückgestellt');expect(runtime.statuses[source.id].ok).toBe(true);await runtime.close();});

it('isolates a nonpositive-duration source record and protects its existing target copy',()=>{const invalid={id:'bad-time',start:{date:'2026-04-01'},end:{date:'2026-04-01'}},good={...invalid,id:'healthy',end:{date:'2026-04-02'}},snapshot={events:[invalid,good],complete:true as const,scope:'all-events' as const};const sourceWithTarget={...source,calendarId:'output'},plan=safeGoogleSourcePlan(snapshot,sourceWithTarget,'output');expect(plan.items).toHaveLength(1);expect(plan.stats.quarantinedGroups).toBe(1);expect(plan.stats.uids).toBe(1);expect(plan.protectedMasterKeys).toHaveLength(1);const validEarlier=googleSourcePlan([{...invalid,end:{date:'2026-04-02'}}],sourceWithTarget,'output').items[0];const reconciled=reconcileGoogleMasters(plan,snapshot,sourceWithTarget,'output',[{id:validEarlier.key,...validEarlier.event}]);expect(reconciled.items).toHaveLength(1);expect(reconciled.stats.reconciledCancellations).toBe(0);});
it('invalid global filter rules still fail instead of quarantining every record',()=>expect(()=>safeGoogleSourcePlan({events:[master],complete:true,scope:'all-events'},{...source,rules:{...source.rules,excludeRegex:'('}})).toThrow());
