import {it,expect,vi} from 'vitest';
import {GoogleRequestGate,GoogleCooldownError,GoogleWriteUncertainError,GoogleRetryExhaustedError} from '../server/google-rate-limit';
import {GoogleClient} from '../server/google';import {CONFIG} from './fixtures';
const url=new URL('https://www.googleapis.com/calendar/v3/calendars/synthetic/events/synthetic');
const quota=(status=403,reason='rateLimitExceeded',headers:Record<string,string>={})=>Response.json({error:{message:'Rate Limit Exceeded',errors:[{reason}]}},{status,headers});
function clock(){let now=0;const sleeps:number[]=[];return {now:()=>now,set:(value:number)=>now=value,sleeps,options:{now:()=>now,random:()=>0,requestIntervalMs:0,writeIntervalMs:0,sleep:async(ms:number)=>{sleeps.push(ms);now+=ms;}}};}
async function failure(job:Promise<unknown>){try{await job;throw Error('Expected quota rejection');}catch(e){return e as any;}}
it('first known403 schedules ten minutes without immediate replay',async()=>{const c=clock(),transport=vi.fn(async()=>quota()),gate=new GoogleRequestGate(transport,c.options),e=await failure(gate.fetch(url,{method:'PUT',body:'synthetic-body'}));expect(e.retryAt).toBe(600000);expect(e.quotaAttempt).toBe(1);expect(transport).toHaveBeenCalledTimes(1);expect(c.sleeps).toEqual([]);});
it('progressively doubles403/429 pauses and adds bounded jitter',async()=>{const c=clock(),gate=new GoogleRequestGate(async()=>quota(429),{...c.options,random:()=>.5});for(const delay of [615000,1215000,2415000]){const before=c.now(),e=await failure(gate.fetch(url,{method:'PUT'}));expect(e.retryAt-before).toBe(delay);c.set(e.retryAt);}});
it('honors longer seconds and HTTP-date Retry-After',async()=>{for(const header of ['7200',new Date(9000000).toUTCString()]){const c=clock(),transport=vi.fn(async()=>quota(429,'rateLimitExceeded',{'Retry-After':header})),gate=new GoogleRequestGate(transport,c.options),e=await failure(gate.fetch(url,{method:'GET'}));expect(e.retryAt).toBe(header==='7200'?7200000:9000000);c.set(e.retryAt-1);await expect(gate.fetch(url,{method:'GET'})).rejects.toBeInstanceOf(GoogleCooldownError);expect(transport).toHaveBeenCalledTimes(1);}});
it('shares cooldown across calendars and rejects requests before expiry',async()=>{const c=clock(),transport=vi.fn(async()=>quota()),gate=new GoogleRequestGate(transport,c.options);await failure(gate.fetch(url,{method:'PUT'}));await expect(gate.fetch(new URL('https://www.googleapis.com/calendar/v3/calendars/another/events'),{method:'GET'})).rejects.toBeInstanceOf(GoogleCooldownError);expect(transport).toHaveBeenCalledTimes(1);});
it('stops automatic request attempts after six rate failures',async()=>{const c=clock(),transport=vi.fn(async()=>quota()),gate=new GoogleRequestGate(transport,c.options);for(let attempt=1;attempt<=6;attempt++){const e=await failure(gate.fetch(url,{method:'PUT'}));expect(e.quotaAttempt).toBe(attempt);expect(e.retryExhausted).toBe(attempt===6);c.set(e.retryAt);}await expect(gate.fetch(url,{method:'GET'})).rejects.toBeInstanceOf(GoogleRetryExhaustedError);expect(transport).toHaveBeenCalledTimes(6);});
it('successful reads do not reset failure count; only a complete corresponding run does',async()=>{const c=clock();let read=false;const gate=new GoogleRequestGate(async()=>read?Response.json({}):quota(),c.options);const first=await failure(gate.fetch(url,{method:'PUT'}));c.set(first.retryAt);read=true;await gate.fetch(url,{method:'GET'});read=false;const second=await failure(gate.fetch(url,{method:'PUT'}));expect(second.quotaAttempt).toBe(2);c.set(second.retryAt);gate.successfulRun(['another']);const third=await failure(gate.fetch(url,{method:'PUT'}));expect(third.quotaAttempt).toBe(3);c.set(third.retryAt);gate.successfulRun(['synthetic']);expect((await failure(gate.fetch(url,{method:'PUT'}))).quotaAttempt).toBe(1);});
it('an explicit reset never shortens an active provider pause',async()=>{const c=clock(),transport=vi.fn(async()=>quota(429,'rateLimitExceeded',{'Retry-After':'7200'})),gate=new GoogleRequestGate(transport,c.options);await failure(gate.fetch(url,{method:'PUT'}));gate.resetFailures(['synthetic']);await expect(gate.fetch(url,{method:'PUT'})).rejects.toBeInstanceOf(GoogleCooldownError);expect(transport).toHaveBeenCalledTimes(1);});
it('never retries permission, malformed400 or non-temporal quotaExceeded',async()=>{for(const [status,reason]of [[403,'forbidden'],[403,'quotaExceeded'],[400,'badRequest']] as const){const c=clock(),transport=vi.fn(async(u:any)=>String(u).includes('/token')?Response.json({access_token:'synthetic',expires_in:3600}):quota(status,reason)),g=new GoogleClient({...CONFIG,clientId:'synthetic',clientSecret:'synthetic',refreshToken:'synthetic'},transport,c.options);await expect(g.write('PUT','synthetic',{})).rejects.toThrow('HTTP '+status);expect(transport.mock.calls.filter(([u])=>!String(u).includes('/token'))).toHaveLength(1);expect(c.sleeps).toEqual([]);}});
it('paces shared requests and writes to one calendar',async()=>{const c=clock(),starts:number[]=[];const gate=new GoogleRequestGate(async()=>{starts.push(c.now());return Response.json({});},{...c.options,requestIntervalMs:250,writeIntervalMs:1000});await Promise.all([gate.fetch(url,{method:'PUT'}),gate.fetch(url,{method:'PATCH'}),gate.fetch(url,{method:'GET'}),gate.fetch(new URL('https://www.googleapis.com/calendar/v3/calendars/another/events'),{method:'POST'})]);expect(starts).toEqual([0,1000,1250,1500]);});
it('cancels pacing and does not execute queued requests',async()=>{let waiting=false;const transport=vi.fn(async()=>Response.json({})),gate=new GoogleRequestGate(transport,{...clock().options,requestIntervalMs:250,sleep:(_ms,signal)=>new Promise((_resolve,reject)=>{waiting=true;signal.addEventListener('abort',()=>reject(Error('cancelled')),{once:true});})});await gate.fetch(url,{method:'GET'});const outcome=gate.fetch(url,{method:'PUT'}).catch(e=>e),queued=gate.fetch(url,{method:'GET'}).catch(e=>e);await vi.waitFor(()=>expect(waiting).toBe(true));gate.close();await outcome;await queued;expect(transport).toHaveBeenCalledTimes(1);});
it('rechecks a changed run guard after pacing before any write',async()=>{const c=clock();let valid=true;const transport=vi.fn(async()=>Response.json({})),gate=new GoogleRequestGate(transport,{...c.options,writeIntervalMs:1000,sleep:async ms=>{valid=false;c.set(c.now()+ms);}});await gate.fetch(url,{method:'PUT'});await expect(gate.fetch(url,{method:'PUT'},()=>valid)).rejects.toThrow('Quellkonfiguration');expect(transport).toHaveBeenCalledTimes(1);});
it('marks interrupted in-flight writes uncertain and never retries',async()=>{let entered=false;const transport=vi.fn(async(_u:any,o?:RequestInit)=>new Promise<Response>((_resolve,reject)=>{entered=true;o?.signal?.addEventListener('abort',()=>reject(Error('network cancelled')),{once:true});})),gate=new GoogleRequestGate(transport,clock().options);const outcome=gate.fetch(url,{method:'POST'}).catch(e=>e);await vi.waitFor(()=>expect(entered).toBe(true));gate.close();expect(await outcome).toBeInstanceOf(GoogleWriteUncertainError);expect(transport).toHaveBeenCalledTimes(1);});
it('does not replay write500 or unreadable successful response',async()=>{for(const status of [500,200]){const c=clock(),transport=vi.fn(async(u:any)=>String(u).includes('/token')?Response.json({access_token:'synthetic',expires_in:3600}):new Response('synthetic invalid response',{status})),g=new GoogleClient({...CONFIG,clientId:'synthetic',clientSecret:'synthetic',refreshToken:'synthetic'},transport,c.options);const e=await failure(g.write('POST',undefined,{id:'synthetic'}));expect(status===500?e.uncertainWrites:e.confirmedWrites).toBe(1);expect(transport.mock.calls.filter(([u])=>!String(u).includes('/token'))).toHaveLength(1);}});
