import {describe,it,expect,vi} from 'vitest';
import {sourceSchema} from '../shared/contracts';
import {googleSourcePlan,googleOrigin,reconcileGoogleMasters,ExpiredCursor,type SourceEvent,type AuthoritativeGoogleSnapshot} from '../server/google-source';
import {GoogleClient,syncPlan,type RemoteEvent} from '../server/google';
import {Runtime} from '../server/runtime';
import {CONFIG,SID,FakeGoogle} from './fixtures';
const source=sourceSchema.parse({id:SID,name:'Synthetic',kind:'google',sourceCalendarId:'input',calendarId:'output'});
const event:SourceEvent={id:'source-event',start:{date:'2026-04-01'},end:{date:'2026-04-02'}};
const proof=(events:SourceEvent[]=[]):AuthoritativeGoogleSnapshot=>({events,complete:true,scope:'all-events'});
const plan=()=>googleSourcePlan([],source,'output');
const target=():RemoteEvent=>{const item=googleSourcePlan([event],source,'output').items[0];return {id:item.key,etag:'synthetic-etag',...item.event};};
function port(){const g=Object.assign(new FakeGoogle(),{readEvents:vi.fn(async(_calendar:string,_params:Record<string,string>)=>({items:[] as SourceEvent[],nextSyncToken:'next'})),listOwnedMasters:vi.fn(async(_calendar:string,_source:string,_origin:string)=>structuredClone([...g.events.values()])),listCalendars:async()=>[{id:'input',summary:'Synthetic input',accessRole:'reader' as const,primary:false,writable:false},{id:'output',summary:'Synthetic output',accessRole:'owner' as const,primary:false,writable:true}]});return g;}
const config=()=>({...CONFIG,sources:[source],writes:true,clientId:'synthetic',clientSecret:'synthetic',refreshToken:'synthetic'});
describe('DB-free Google deletion reconciliation',()=>{
 it('plans absence cancellation only for exact master ownership and source origin',()=>{const owned=target(),markers=owned.extendedProperties!.private!;const others:RemoteEvent[]=[{id:'user-created'},{...owned,id:'other-source',extendedProperties:{private:{...markers,source:'other'}}},{...owned,extendedProperties:{private:{...markers,calendar:'other'}}},{...owned,extendedProperties:{private:{...markers,origin:'old-source-calendar'}}},{...owned,extendedProperties:{private:{...markers,key:'wrong'}}},{...owned,extendedProperties:{private:{...markers,origin:undefined} as any}},{...owned,recurringEventId:'parent'},{...owned,status:'cancelled'}];const result=reconcileGoogleMasters(plan(),proof(),source,'output',[owned,...others]);expect(result.items).toEqual([{key:owned.id,cancel:true,reconcileOrigin:googleOrigin(source)}]);expect(result.stats.reconciledCancellations).toBe(1);});
 it('protects existing series whose source master could not be retrieved for a live orphan',()=>{const owned=target();const result=reconcileGoogleMasters(plan(),{...proof(),unresolvedParents:[event.id]},source,'output',[owned]);expect(result.items).toEqual([]);});
 it('never cancels present masters, or infers any missing series instance',()=>{const parent={...event,recurrence:['RRULE:FREQ=DAILY;COUNT=3']};const p=googleSourcePlan([parent],source,'output'),owned=target();expect(reconcileGoogleMasters(p,proof([parent]),source,'output',[owned,{...owned,id:'exception',recurringEventId:owned.id}]).items).toEqual(p.items);});
 it('rejects partial or bounded proof before producing cancellation plans',()=>{for(const p of [{events:[],complete:false,scope:'all-events'},{events:[],complete:true,scope:'time-window'}])expect(()=>reconcileGoogleMasters(plan(),p as any,source,'output',[target()])).toThrow(/vollständigen/);});
 it('recovers missing old tombstones after a process restart without local state',async()=>{const g=port();g.events.set(target().id,target());const runtime=new Runtime(config(),{google:g});await runtime.execute(source.id,true);expect(g.events.get(target().id)?.status).toBe('cancelled');expect(g.calls).toHaveLength(1);expect(g.calls[0].method).toBe('PATCH');expect(g.calls[0].body).toEqual({status:'cancelled'});await runtime.close();const restarted=new Runtime(config(),{google:g});await restarted.execute(source.id,true);expect(g.calls).toHaveLength(1);expect(g.readEvents.mock.calls.at(-1)?.[1]).not.toHaveProperty('syncToken');});
 it('reconciles a 410 full reset even when the deleted source tombstone expired',async()=>{const g=port();g.events.set(target().id,target());g.readEvents.mockResolvedValueOnce({items:[event],nextSyncToken:'first'}).mockRejectedValueOnce(new ExpiredCursor()).mockResolvedValueOnce({items:[],nextSyncToken:'reset'});const runtime=new Runtime(config(),{google:g});await runtime.execute(source.id);await runtime.execute(source.id,true);expect(g.calls).toHaveLength(1);expect(g.calls[0].body.status).toBe('cancelled');expect(g.readEvents.mock.calls[2][1]).not.toHaveProperty('syncToken');});
 it('does not reconcile or write when source page two fails',async()=>{const g=port();g.events.set(target().id,target());g.readEvents.mockResolvedValueOnce({items:[],nextSyncToken:'unused',nextPageToken:'page2'} as any).mockRejectedValueOnce(new Error('synthetic page failure'));const runtime=new Runtime(config(),{google:g});await expect(runtime.execute(source.id,true)).rejects.toThrow();expect(g.listOwnedMasters).not.toHaveBeenCalled();expect(g.calls).toEqual([]);});
 it('does not write when destination inventory fails after a complete source read',async()=>{const g=port();g.events.set(target().id,target());g.listOwnedMasters.mockRejectedValueOnce(new Error('synthetic target failure'));await expect(new Runtime(config(),{google:g}).execute(source.id,true)).rejects.toThrow();expect(g.calls).toEqual([]);});
 it('refuses inferred cancellation when target preflight has no ETag',async()=>{const g=new FakeGoogle(),owned=target();g.events.set(owned.id,{...owned,etag:undefined});await expect(syncPlan(reconcileGoogleMasters(plan(),proof(),source,'output',[owned]),source,g)).rejects.toThrow(/Besitzmarkierung/);expect(g.calls).toEqual([]);});
 it('rechecks ownership changes before any write, including source origin',async()=>{const g=new FakeGoogle(),owned=target();g.events.set(owned.id,{...owned,extendedProperties:{private:{...owned.extendedProperties!.private,origin:'changed'}}});const p=reconcileGoogleMasters(plan(),proof(),source,'output',[owned]);await expect(syncPlan(p,source,g)).rejects.toThrow(/Besitzmarkierung/);expect(g.calls).toEqual([]);});
 it('reads every destination page with exact property filters and no time bounds or private details',async()=>{const calls:URL[]=[];const fetcher=vi.fn(async(url:any)=>{const u=new URL(String(url));calls.push(u);if(u.pathname.endsWith('/token'))return Response.json({access_token:'synthetic',expires_in:3600});return Response.json(u.searchParams.has('pageToken')?{accessRole:'owner',items:[{id:'two'}]}:{accessRole:'owner',items:[{id:'one'}],nextPageToken:'page2'});});const client=new GoogleClient(config(),fetcher);expect(await client.listOwnedMasters('output',source.id,googleOrigin(source))).toHaveLength(2);const request=calls[1];expect(request.searchParams.getAll('privateExtendedProperty')).toEqual(['icsSync=v1','source='+source.id,'calendar=output','origin='+googleOrigin(source)]);for(const field of ['timeMin','timeMax','syncToken','q'])expect(request.searchParams.has(field)).toBe(false);expect(request.searchParams.get('fields')).not.toMatch(/summary|description|attendees/);expect(calls[2].searchParams.get('pageToken')).toBe('page2');});
 it('fails closed on repeated destination pages, lost permission, malformed and oversized inventories',async()=>{for(const reply of [{accessRole:'owner',items:[],nextPageToken:'same'},{accessRole:'reader',items:[]},{accessRole:'owner',items:'invalid'},{accessRole:'owner',items:[],nextPageToken:0},{accessRole:'owner',items:Array.from({length:10001},(_,i)=>({id:String(i)}))}]){const fetcher=vi.fn(async(url:any)=>String(url).includes('/token')?Response.json({access_token:'synthetic',expires_in:3600}):Response.json(reply));await expect(new GoogleClient(config(),fetcher).listOwnedMasters('output',source.id,googleOrigin(source))).rejects.toThrow();}});
 it('requires an authoritative source access role and includes hidden invitations without bounded filters',async()=>{const fetcher=vi.fn(async(url:any)=>String(url).includes('/token')?Response.json({access_token:'synthetic',expires_in:3600}):Response.json({accessRole:'freeBusyReader',items:[],nextSyncToken:'bad'}));await expect(new GoogleClient(config(),fetcher).readEvents('input',{})).rejects.toThrow(/vollständige/);const u=new URL(String(fetcher.mock.calls[1][0]));expect(u.searchParams.get('showHiddenInvitations')).toBe('true');expect(u.searchParams.get('fields')).toContain('accessRole');});
 it('previews inferred cancellations without target writes and cannot consume them before sync',async()=>{const g=port();g.events.set(target().id,target());const runtime=new Runtime(config(),{google:g});const preview=await runtime.execute(source.id) as any;expect(preview.stats.reconciledCancellations).toBe(1);expect(g.calls).toEqual([]);await runtime.execute(source.id,true);expect(g.calls).toHaveLength(1);});
});
