import{describe,it,expect,vi}from'vitest';import{parseCalendar}from'../server/calendar';import{syncPlan,sameTime,GoogleClient}from'../server/google';import{ics,MASTER,BASE,EX,SID,SOURCE,CONFIG,FakeGoogle}from'./fixtures';
describe('Google adapter with synthetic doubles',()=>{
 it('is idempotent for moved instances and preserves IDs',async()=>{const p=parseCalendar(ics([MASTER,EX]),SID),g=new FakeGoogle();await syncPlan(p,SOURCE,g);await syncPlan(p,SOURCE,g);expect(g.events.size).toBe(2);expect(g.calls.map(c=>c.method)).toEqual(['POST','PUT']);await syncPlan(parseCalendar(ics([MASTER,EX.replaceAll('20260331','20260401')]),SID),SOURCE,g);expect(g.events.size).toBe(2);});
 it('converges after partial failure without duplicate insertion',async()=>{const p=parseCalendar(ics([MASTER,EX]),SID),g=new FakeGoogle();g.failAt=2;await expect(syncPlan(p,SOURCE,g)).rejects.toThrow();g.failAt=0;await syncPlan(p,SOURCE,g);expect(g.events.size).toBe(2);expect(g.calls.filter(c=>c.method==='POST')).toHaveLength(1);});
 it('cancels and restores the same exception instance',async()=>{const p=parseCalendar(ics([MASTER,EX]),SID),g=new FakeGoogle();await syncPlan(p,SOURCE,g);const id=[...g.events.keys()].find(id=>id!==p.items[0].key)!;await syncPlan(parseCalendar(ics([MASTER,'UID:synthetic-uid\r\nRECURRENCE-ID:20260330T080000Z\r\nSTATUS:CANCELLED']),SID),SOURCE,g);expect(g.events.get(id)?.status).toBe('cancelled');await syncPlan(p,SOURCE,g);expect(g.events.get(id)?.status).toBe('confirmed');expect(g.events.size).toBe(2);});
 it('does nothing for absent UIDs or absent exceptions',async()=>{const p=parseCalendar(ics([MASTER,EX]),SID),g=new FakeGoogle();await syncPlan(p,SOURCE,g);const old=structuredClone([...g.events.values()].find(e=>e.recurringEventId));g.calls=[];await syncPlan(parseCalendar(ics([MASTER]),SID),SOURCE,g);expect([...g.events.values()].find(e=>e.recurringEventId)).toEqual(old);expect(g.calls).toEqual([]);g.calls=[];await syncPlan(parseCalendar(ics(),SID),SOURCE,g);expect(g.calls).toEqual([]);});
 it('preflights all ownership before any writes',async()=>{const p=parseCalendar(ics([BASE.replace('UID:synthetic-uid','UID:new'),BASE]),SID),g=new FakeGoogle();g.events.set(p.items[1].key,{id:p.items[1].key,extendedProperties:{private:{source:'foreign'}}});await expect(syncPlan(p,SOURCE,g)).rejects.toThrow(/gehört/);expect(g.calls).toEqual([]);});
 it('refuses shortened bounded recurrence before writes',async()=>{const g=new FakeGoogle();await syncPlan(parseCalendar(ics([MASTER]),SID),SOURCE,g);g.calls=[];const plan=parseCalendar(ics([BASE.replace('UID:synthetic-uid','UID:new'),MASTER.replace('COUNT=4','COUNT=1')],'X-CLIPSTART:20261001T000000Z\r\n'),SID);await expect(syncPlan(plan,SOURCE,g)).rejects.toThrow(/Serienstruktur/);expect(g.calls).toEqual([]);});
 it('only cancels explicitly represented owned exclusions',async()=>{const g=new FakeGoogle(),p=parseCalendar(ics([BASE]),SID);await syncPlan(p,SOURCE,g);await syncPlan(parseCalendar(ics([BASE.replace('BUSYSTATUS:BUSY','BUSYSTATUS:FREE')]),SID),SOURCE,g);expect(g.events.get(p.items[0].key)?.status).toBe('cancelled');const fresh=new FakeGoogle();await syncPlan(parseCalendar(ics([BASE.replace('BUSYSTATUS:BUSY','BUSYSTATUS:FREE')]),SID),SOURCE,fresh);expect(fresh.calls).toEqual([]);});
 it('refuses missing original instance without inserting an exception',async()=>{const g=new FakeGoogle();g.missingInstances=true;await expect(syncPlan(parseCalendar(ics([MASTER,EX]),SID),SOURCE,g)).rejects.toThrow(/nicht eindeutig/);expect(g.calls.filter(c=>c.method==='POST')).toHaveLength(1);});
 it('compares UTC instants and exclusive dates',()=>{expect(sameTime({dateTime:'2026-03-30T10:00:00+02:00',timeZone:'Europe/Berlin'},{dateTime:'2026-03-30T08:00:00Z',timeZone:'UTC'})).toBe(true);expect(sameTime({date:'2026-03-30'},{date:'2026-03-30'})).toBe(true);expect(sameTime({date:'2026-03-30'},{dateTime:'2026-03-30T00:00:00Z',timeZone:'UTC'})).toBe(false);});
 it('uses originalStart pagination and ETags without sending source details',async()=>{const requests:{url:string;options:RequestInit}[]=[];let pages=0;const transport=vi.fn(async(url:any,options:RequestInit={})=>{requests.push({url:String(url),options});if(String(url).includes('/token'))return Response.json({access_token:'synthetic-only',expires_in:3600});if(String(url).includes('/instances'))return Response.json(++pages===1?{items:[{id:'first'}],nextPageToken:'page2'}:{items:[{id:'second'}]});return Response.json({id:'event'});});const client=new GoogleClient({...CONFIG,clientId:'synthetic',clientSecret:'synthetic',refreshToken:'synthetic',calendarId:'synthetic-target'},transport);expect(await client.instances('parent',{dateTime:'2026-03-30T08:00:00Z',timeZone:'UTC'})).toHaveLength(2);expect(new URL(requests[1].url).searchParams.get('originalStart')).toBe('2026-03-30T08:00:00Z');expect(new URL(requests[2].url).searchParams.get('pageToken')).toBe('page2');await client.write('PATCH','event',{status:'cancelled'},'etag');expect(requests.at(-1)?.options.headers).toMatchObject({'If-Match':'etag'});expect(requests.filter(r=>r.url.includes('/token'))).toHaveLength(1);});
 it('rejects non-insert conflicts and sanitizes remote error bodies',async()=>{const transport=vi.fn(async(url:any)=>String(url).includes('/token')?Response.json({access_token:'synthetic',expires_in:3600}):new Response('PRIVATE REMOTE DETAILS',{status:409}));const client=new GoogleClient({...CONFIG,clientId:'synthetic',clientSecret:'synthetic',refreshToken:'synthetic'},transport);await expect(client.write('PUT','x',{})).rejects.toThrow('HTTP 409');expect(await client.write('POST',undefined,{})).toMatchObject({conflict:true});});
 it('rejects foreign ownership on an exception',async()=>{const p=parseCalendar(ics([MASTER,EX]),SID),g=new FakeGoogle();await syncPlan(p,SOURCE,g);for(const e of g.events.values())if(e.recurringEventId)e.extendedProperties={private:{source:'foreign'}};await expect(syncPlan(p,SOURCE,g)).rejects.toThrow(/fremde/);});
});
