import {Runtime} from '../server/runtime';
import {createApp} from '../server/app';
import {exportConfiguration} from '../server/env-export';
import {configuredSources} from '../server/config';
import {HEAD} from './fixtures';
import {describe,it,expect,vi} from 'vitest';
import {GoogleSourceReader,googleSourcePlan,validateSourceGraph,ExpiredCursor,type SourceEvent} from '../server/google-source';
import {GoogleClient,syncPlan} from '../server/google';
import {sourceSchema} from '../shared/contracts';
import {CONFIG,SID,FakeGoogle} from './fixtures';
const source=sourceSchema.parse({id:SID,name:'Synthetic Google',kind:'google',sourceCalendarId:'input',calendarId:'output'});
const event:SourceEvent={id:'master',summary:'PRIVATE topic',start:{dateTime:'2026-03-23T10:00:00+01:00',timeZone:'Europe/Berlin'},end:{dateTime:'2026-03-23T11:00:00+01:00',timeZone:'Europe/Berlin'},recurrence:['RRULE:FREQ=WEEKLY;COUNT=4'],attendees:[{responseStatus:'accepted'}]};
describe('Google sources using synthetic fixtures only',()=>{
 it('requires a distinct source identity and exports validated settings',()=>{expect(sourceSchema.safeParse({...source,sourceCalendarId:undefined}).success).toBe(false);expect(()=>validateSourceGraph([source],'')).not.toThrow();expect(()=>validateSourceGraph([{...source,calendarId:'input'}],'')).toThrow(/Kopierschleife/);});
 it('rejects cycles across disabled sources and global targets',()=>{expect(()=>validateSourceGraph([source,{...source,id:crypto.randomUUID(),sourceCalendarId:'output',calendarId:'input'}],'')).toThrow();expect(()=>validateSourceGraph([{...source,calendarId:''}],'input')).toThrow();});
 it('preserves recurrence zones, moved exceptions, cancellation and privacy',()=>{
  const plan=googleSourcePlan([event,{id:'moved',recurringEventId:'master',originalStartTime:{dateTime:'2026-03-30T10:00:00+02:00',timeZone:'Europe/Berlin'},start:{dateTime:'2026-03-31T12:00:00Z',timeZone:'UTC'},end:{dateTime:'2026-03-31T13:00:00Z',timeZone:'UTC'}},{id:'cancel',status:'cancelled',recurringEventId:'master',originalStartTime:{dateTime:'2026-04-06T08:00:00Z',timeZone:'UTC'}}],{...source,rules:{...source.rules,acceptedCount:true}},'output');
  expect(plan.items).toHaveLength(3);expect(plan.items[0].event).toMatchObject({summary:'Termin · 1 👤',start:{timeZone:'Europe/Berlin'},recurrence:event.recurrence});expect(plan.items[1].original?.dateTime).toBe('2026-03-30T10:00:00+02:00');expect(plan.items[2].cancel).toBe(true);expect(JSON.stringify(plan)).not.toContain('PRIVATE');
 });
 it('preserves all-day exclusive end and stable IDs independent of title',()=>{const e={id:'day',start:{date:'2026-04-01'},end:{date:'2026-04-03'}};const first=googleSourcePlan([e],source,'output');expect(first.items[0].event?.end).toEqual(e.end);expect(googleSourcePlan([{...e,summary:'changed'}],source,'output').items[0].key).toBe(first.items[0].key);expect(googleSourcePlan([e],{...source,sourceCalendarId:'other'},'output').items[0].key).not.toBe(first.items[0].key);});
 it('maps deletions and filters only explicitly represented IDs',()=>{const plan=googleSourcePlan([{id:'gone',status:'cancelled'},{...event,transparency:'transparent'},{...event,id:'lunch',summary:'Mittagspause'}],source,'output');expect(plan.items.every(i=>i.cancel)).toBe(true);expect(plan.items).toHaveLength(3);expect(googleSourcePlan([],source,'output').items).toEqual([]);});
 it('excludes managed masters and their exceptions to prevent feedback',()=>{expect(googleSourcePlan([{...event,extendedProperties:{private:{icsSync:'v1'}}},{...event,id:'exception',recurringEventId:'master'}],source,'output').items).toEqual([]);});
 it('fails closed on orphan exceptions and recurrence injection',()=>{expect(()=>googleSourcePlan([{...event,recurringEventId:'absent'}],source)).toThrow();expect(()=>googleSourcePlan([{...event,recurrence:['RRULE:FREQ=DAILY\r\nSUMMARY:bad']}],source)).toThrow();});
 it('reads all pages before committing token and retains full incremental snapshot',async()=>{const reader=new GoogleSourceReader(),readEvents=vi.fn().mockResolvedValueOnce({items:[event],nextPageToken:'p2'}).mockResolvedValueOnce({items:[],nextSyncToken:'t1'}).mockResolvedValueOnce({items:[{id:'gone',status:'cancelled'}],nextSyncToken:'t2'});expect(await reader.read('input',{readEvents})).toHaveLength(1);expect(await reader.read('input',{readEvents})).toHaveLength(2);expect(readEvents.mock.calls[1][1]).toMatchObject({pageToken:'p2'});expect(readEvents.mock.calls[2][1]).toMatchObject({syncToken:'t1'});});
 it('keeps prior cursor on partial failure and retries the delta',async()=>{const reader=new GoogleSourceReader(),readEvents=vi.fn().mockResolvedValueOnce({items:[event],nextSyncToken:'t1'}).mockResolvedValueOnce({items:[{id:'gone',status:'cancelled'}],nextPageToken:'p'}).mockRejectedValueOnce(new Error('synthetic failure')).mockResolvedValueOnce({items:[],nextSyncToken:'t2'});await reader.read('input',{readEvents});await expect(reader.read('input',{readEvents})).rejects.toThrow();expect(await reader.read('input',{readEvents})).toEqual([event]);expect(readEvents.mock.calls[3][1].syncToken).toBe('t1');});
 it('resets expired cursor without synthesizing deletions',async()=>{const reader=new GoogleSourceReader(),readEvents=vi.fn().mockResolvedValueOnce({items:[event],nextSyncToken:'t1'}).mockRejectedValueOnce(new ExpiredCursor()).mockResolvedValueOnce({items:[],nextSyncToken:'new'});await reader.read('input',{readEvents});expect(await reader.read('input',{readEvents})).toEqual([]);expect(readEvents.mock.calls[2][1]).not.toHaveProperty('syncToken');});
 it('rejects repeated pages, absent cursors and oversize snapshots',async()=>{await expect(new GoogleSourceReader().read('input',{readEvents:vi.fn().mockResolvedValue({items:[],nextPageToken:'same'})})).rejects.toThrow(/paginierung/i);await expect(new GoogleSourceReader().read('input',{readEvents:vi.fn().mockResolvedValue({items:[]})})).rejects.toThrow(/cursor/);await expect(new GoogleSourceReader().read('input',{readEvents:vi.fn().mockResolvedValue({items:Array.from({length:10001},(_,i)=>({id:String(i)})),nextSyncToken:'x'})})).rejects.toThrow(/groß/);});
 it('uses bounded Google fields and propagates 410 only for source reads',async()=>{const fetcher=vi.fn(async(url:any)=>String(url).includes('/token')?Response.json({access_token:'synthetic',expires_in:3600}):new Response('',{status:410}));const client=new GoogleClient({...CONFIG,clientId:'synthetic',clientSecret:'synthetic',refreshToken:'synthetic'},fetcher);await expect(client.readEvents('input',{syncToken:'t'})).rejects.toBeInstanceOf(ExpiredCursor);const url=new URL(String(fetcher.mock.calls[1][0]));expect(url.searchParams.get('fields')).not.toContain('description');expect(await client.get('gone')).toBeNull();});
 it('updates explicit native Google series structure using the same target ID',async()=>{const google=new FakeGoogle();await syncPlan(googleSourcePlan([event],source,'output'),source,google);await syncPlan(googleSourcePlan([{...event,recurrence:['RRULE:FREQ=WEEKLY;COUNT=5']}],source,'output'),source,google);expect(google.events.size).toBe(1);expect(google.calls.at(-1)?.method).toBe('PUT');});
});

describe('Google source integration',()=>{
 const calendars=[{id:'input',summary:'Synthetic input',accessRole:'reader' as const,primary:false,writable:false},{id:'output',summary:'Synthetic output',accessRole:'owner' as const,primary:false,writable:true}];
 const port=()=>({listOwnedMasters:vi.fn(async()=>[]),get:async()=>null,instances:async()=>[],write:vi.fn(async()=>null),listCalendars:async()=>calendars,readEvents:vi.fn(async(_calendar:string,_params:Record<string,string>)=>({items:[event],nextSyncToken:'next'}))});
 it('exports source calendar without tokens and roundtrips through ENV',()=>{const exported=exportConfiguration([source],'');expect(configuredSources(exported.SOURCES_JSON)[0]).toEqual(source);expect(exported.env).toContain('sourceCalendarId');expect(exported.env).not.toContain('nextSyncToken');});
 it('accepts readonly source and rejects identical calendars without mutating runtime',async()=>{const google=port(),runtime=new Runtime({...CONFIG,sources:[]},{google}),app=createApp(runtime.config,runtime).app;const accepted=await app.request('/api/sources',{method:'POST',headers:HEAD,body:JSON.stringify(source)});expect(accepted.status).toBe(201);const rejected=await app.request('/api/sources/'+source.id,{method:'PUT',headers:HEAD,body:JSON.stringify({...source,sourceCalendarId:'output'})});expect(rejected.status).toBe(400);expect(runtime.sources[0].sourceCalendarId).toBe('input');});
 it('previews read-only polling and keeps scheduling inactive by default',async()=>{const google=port(),runtime=new Runtime({...CONFIG,sources:[source],writes:false},{google});await runtime.tick();expect(google.readEvents).not.toHaveBeenCalled();runtime.sources[0].enabled=true;await runtime.tick(1000);expect(google.readEvents).toHaveBeenCalledOnce();await runtime.tick(2000);expect(google.readEvents).toHaveBeenCalledOnce();expect(google.write).not.toHaveBeenCalled();expect(runtime.statuses[source.id].mode).toBe('preview');await runtime.close();});
 it('remaps cached snapshot after filter changes and preview never consumes the later plan',async()=>{const google=port(),runtime=new Runtime({...CONFIG,sources:[source]},{google});const first=await runtime.execute(source.id);runtime.sources[0].rules.excludeRegex='PRIVATE';const second=await runtime.execute(source.id);expect((first as any).items[0].cancel).toBe(false);expect((second as any).items[0].cancel).toBe(true);expect(google.readEvents.mock.calls[1][1]).toMatchObject({syncToken:'next'});});
 it('refuses inadequate source roles before event reads',async()=>{const google={...port(),listCalendars:async()=>calendars.map(c=>({...c,accessRole:'freeBusyReader' as const}))},runtime=new Runtime({...CONFIG,sources:[source]},{google});await expect(runtime.execute(source.id)).rejects.toThrow(/Leseberechtigung/);expect(google.readEvents).not.toHaveBeenCalled();});
 it('quarantines unmappable records and repairs them on a later valid delta',async()=>{const google=port();google.readEvents.mockResolvedValueOnce({items:[{...event,end:undefined}],nextSyncToken:'bad'});const runtime=new Runtime({...CONFIG,sources:[source]},{google});expect((await runtime.execute(source.id) as any).stats.quarantinedGroups).toBe(1);expect((await runtime.execute(source.id) as any).stats.upserts).toBe(1);expect(google.readEvents.mock.calls[1][1]).toMatchObject({syncToken:'bad'});});

 it('cancels deleted series even when cached confirmed exceptions remain',()=>{const plan=googleSourcePlan([{id:'master',status:'cancelled'},{...event,id:'exception',recurringEventId:'master',originalStartTime:event.start}],source,'output');expect(plan.items).toHaveLength(1);expect(plan.items[0].cancel).toBe(true);});

 it('invalidates the snapshot after invalid global rules before a repaired full read',async()=>{const google=port(),runtime=new Runtime({...CONFIG,sources:[source]},{google});runtime.sources[0].rules.excludeRegex='(';await expect(runtime.execute(source.id)).rejects.toThrow();runtime.sources[0].rules.excludeRegex='';await runtime.execute(source.id);expect(google.readEvents.mock.calls[1][1]).not.toHaveProperty('syncToken');});

});
