import {describe,it,expect} from 'vitest';
import {parseCalendar} from '../server/calendar';
import {googleSourcePlan} from '../server/google-source';
import {anonymousTitle} from '../server/event-title';
import {syncPlan} from '../server/google';
import {sourceSchema} from '../shared/contracts';
import {exportConfiguration} from '../server/env-export';
import {SID,SOURCE,FakeGoogle,ics,BASE,MASTER} from './fixtures';
const source=sourceSchema.parse({...SOURCE,kind:'google',sourceCalendarId:'input',rules:{acceptedCount:true}});
const googleEvent={id:'event',start:{date:'2026-04-01'},end:{date:'2026-04-02'},location:'PRIVATE room'};
describe('compact accepted counts and explicit location privacy',()=>{
 it('omits unknown counts and prevents a duplicate count when pseudonyms express it',()=>{expect(anonymousTitle(true,undefined)).toBe('Termin');expect(anonymousTitle(true,0)).toBe('Termin · 0 👤');expect(anonymousTitle(true,3)).toBe('Termin · 3 👤');expect(anonymousTitle(true,3,['Person 1','Person 2','Person 3'])).toBe('Termin');expect(anonymousTitle(true,2,['Person 1','Person 2','Person 3'])).toBe('Termin · 2 👤');expect(anonymousTitle(false,3)).toBe('Termin');});
 it.each([['ACCEPTED','Termin · 1 👤'],['DECLINED','Termin · 0 👤'],['TENTATIVE','Termin · 0 👤'],['NEEDS-ACTION','Termin · 0 👤'],['','Termin']])('ICS response %s counts only known accepted responses', (status,title)=>{const line='ATTENDEE'+(status?';PARTSTAT='+status:'')+':mailto:PRIVATE@example.invalid';const plan=parseCalendar(ics([BASE+'\r\n'+line]),SID,{acceptedCount:true});expect(plan.items[0].event?.summary).toBe(title);expect(JSON.stringify(plan)).not.toContain('example.invalid');});
 it('omits absent or partly unknown ICS attendee data rather than inventing zero',()=>{expect(parseCalendar(ics([BASE]),SID,{acceptedCount:true}).items[0].event?.summary).toBe('Termin');const partial=BASE+'\r\nATTENDEE;PARTSTAT=ACCEPTED:urn:a\r\nATTENDEE:urn:b';expect(parseCalendar(ics([partial]),SID,{acceptedCount:true}).items[0].event?.summary).toBe('Termin');});
 it.each([['accepted','Termin · 1 👤'],['declined','Termin · 0 👤'],['tentative','Termin · 0 👤'],['needsAction','Termin · 0 👤'],[undefined,'Termin']])('Google response %s counts only known accepted responses', (status,title)=>{const plan=googleSourcePlan([{...googleEvent,attendees:[{responseStatus:status}]}],source);expect(plan.items[0].event?.summary).toBe(title);expect(plan.items[0].event).not.toHaveProperty('attendees');});
 it('omits Google absent, empty or explicitly omitted attendance',()=>{for(const event of [googleEvent,{...googleEvent,attendees:[]},{...googleEvent,attendees:[{responseStatus:'accepted'}],attendeesOmitted:true}])expect(googleSourcePlan([event],source).items[0].event?.summary).toBe('Termin');});
 it('default location is scrubbed in both inputs; opting in exposes only the location',()=>{const raw=BASE+'\r\nLOCATION:PRIVATE room\r\nDESCRIPTION:PRIVATE description';expect(parseCalendar(ics([raw]),SID).items[0].event).not.toHaveProperty('location');expect(googleSourcePlan([googleEvent],source).items[0].event).not.toHaveProperty('location');const opted=sourceSchema.parse({...source,rules:{...source.rules,includeLocation:true}});expect(parseCalendar(ics([raw]),SID,opted.rules).items[0].event?.location).toBe('PRIVATE room');expect(googleSourcePlan([googleEvent],opted).items[0].event?.location).toBe('PRIVATE room');expect(JSON.stringify(parseCalendar(ics([raw]),SID,opted.rules))).not.toContain('description');expect(JSON.parse(exportConfiguration([opted],'').SOURCES_JSON)[0].rules.includeLocation).toBe(true);});
 it('explicitly clears an old location on recurring PATCH when the option is switched off',async()=>{const google=new FakeGoogle(),withLocation=parseCalendar(ics([MASTER+'\r\nLOCATION:PRIVATE room']),SID,{includeLocation:true}),without=parseCalendar(ics([MASTER+'\r\nLOCATION:PRIVATE room']),SID,{includeLocation:false});await syncPlan(withLocation,SOURCE,google);await syncPlan(without,SOURCE,google);expect(google.calls.at(-1)?.method).toBe('PATCH');expect(google.calls.at(-1)?.body.location).toBe('');expect(google.events.get(withLocation.items[0].key)).toMatchObject({location:''});});
});
