import {it,expect} from 'vitest';
import {parseCalendar} from '../server/calendar';
import {previewSnapshot,type SnapshotScope} from '../server/snapshot-preview';
import {syncPlan,type RemoteEvent} from '../server/google';
import {ics,MASTER,EX,SOURCE,SID,FakeGoogle} from './fixtures';
const source={...SOURCE,calendarId:'synthetic-output'};
const scope:SnapshotScope={authority:'window',window:{start:'2026-03-01',end:'2026-05-01',timezone:'Europe/Berlin'}};
function fixture(){const plan=parseCalendar(ics([MASTER]),SID,{},source.calendarId),old=parseCalendar(ics([MASTER,EX]),SID,{},source.calendarId);const master={id:plan.items[0]!.key,...plan.items[0]!.event!,etag:'master'};const item=old.items.find(i=>i.parent)!;const exception:RemoteEvent={id:'synthetic_instance',...item.event!,etag:'exception',recurringEventId:master.id,originalStartTime:item.original};return {plan,master,exception};}
it('proposes restoring a disappeared moved exception only in an explicit complete window',()=>{const {plan,master,exception}=fixture();const p=previewSnapshot(plan,source,[master,exception],scope);expect(p.proposedRestores).toHaveLength(1);expect(p.proposedRestores[0]!.event!.start.dateTime).toContain('2026-03-30T10:00');expect(p.restoreEtags).toEqual({[master.id]:'master',[p.proposedRestores[0]!.key]:'exception'});expect(previewSnapshot(plan,source,[master,exception],{authority:'unknown'}).protectedAbsent).toBe(1);});
it('restores with instance If-Match and rejects a changed parent before writes',async()=>{for(const changed of [false,true]){const {plan,master,exception}=fixture();plan.items.push(...previewSnapshot(plan,source,[master,exception],scope).proposedRestores);const g=new FakeGoogle();g.events.set(master.id,{...master,etag:changed?'changed':'master'});g.events.set(exception.id,exception);if(changed){await expect(syncPlan(plan,source,g)).rejects.toThrow('Serienmaster');expect(g.calls).toHaveLength(0);}else{await syncPlan(plan,source,g);expect(g.calls).toHaveLength(1);expect(g.calls[0]!.etag).toBe('exception');expect(g.calls[0]!.body.recurrence).toBeUndefined();}}});
it('protects foreign, boundary-crossing, unsupported, excluded and cancelled exceptions without timing',()=>{for(const kind of ['foreign','outside','rule','exdate','cancelled']){const {plan,master,exception}=fixture();if(kind==='foreign')exception.extendedProperties!.private!.source='other';if(kind==='outside')exception.end={dateTime:'2026-05-02T10:00:00Z',timeZone:'UTC'};if(kind==='rule')plan.items[0]!.event!.recurrence=['RRULE:FREQ=DAILY;COUNT=4'];if(kind==='exdate')plan.items[0]!.event!.recurrence!.push('EXDATE:20260330T080000Z');if(kind==='cancelled'){exception.status='cancelled';delete (exception as any).start;delete (exception as any).end;}expect(previewSnapshot(plan,source,[master,exception],scope).proposedRestores).toHaveLength(0);}});
it('never restores an explicitly cancelled incoming exception',()=>{const {master,exception}=fixture(),plan=parseCalendar(ics([MASTER,EX+'\r\nSTATUS:CANCELLED']),SID,{},source.calendarId);expect(previewSnapshot(plan,source,[master,exception],scope).proposedRestores).toHaveLength(0);});

it('protects missing exceptions while the incoming master metadata changes',()=>{const {plan,master,exception}=fixture();plan.items[0]!.event!.summary='Synthetic replacement metadata';const preview=previewSnapshot(plan,source,[master,exception],scope);expect(preview.proposedRestores).toHaveLength(0);expect(preview.protectedAbsent).toBe(1);});
