import {validClipHistory,type ClipHistory} from './snapshot-history.js';
import {promises as fs,constants} from 'node:fs';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {AppError} from './errors.js';
export interface Approval {revision:string;signature:string;removals:string[];removalEtags:Record<string,string>;emptyConfirmed:boolean;seriesEtags?:Record<string,string>}
export interface InputFile {relativePath:string;hash:string;dev:string;ino:string;size:string;mtimeNs:string;ctimeNs:string}
export interface CleanupRecord {file:InputFile;stage:string;mode:'archive'|'delete';phase:'intent'|'claimed'|'done'|'retained';archive?:string}
export interface SourceState {version:1;source:string;approval?:Approval;clipHistory?:ClipHistory;cleanup?:{signature:string;records:CleanupRecord[]}}
export class DataStore {
 constructor(readonly directory:string|undefined){}
 private async root(){if(!this.directory)throw new AppError('DATA_DIR und geschützter Datenmount fehlen.');try{const root=await fs.realpath(this.directory),s=await fs.stat(root);if(!s.isDirectory()||(s.mode&0o077)!==0)throw Error();return root;}catch{throw new AppError('Datenverzeichnis benötigt Zugriff und Rechte 0700.');}}
 private validId(id:string){if(!/^[0-9a-f-]{36}$/i.test(id))throw new AppError('Datenquell-ID ungültig.');}
 async read(id:string):Promise<SourceState>{this.validId(id);if(!this.directory)return {version:1,source:id};const root=await this.root();let h:Awaited<ReturnType<typeof fs.open>>|undefined;try{h=await fs.open(path.join(root,id+'.json'),constants.O_RDONLY|constants.O_NOFOLLOW);const s=await h.stat();if(!s.isFile()||s.size>262144||(s.mode&0o077)!==0)throw Error();const state=JSON.parse(await h.readFile('utf8'));if(state.version!==1||state.source!==id||state.clipHistory&&!validClipHistory(state.clipHistory)||state.approval&&(!/^[a-f0-9]{64}$/.test(state.approval.revision)||typeof state.approval.signature!=='string'||typeof state.approval.emptyConfirmed!=='boolean'||state.approval.seriesEtags!==undefined&&(!state.approval.seriesEtags||Array.isArray(state.approval.seriesEtags)||typeof state.approval.seriesEtags!=='object'||Object.entries(state.approval.seriesEtags).some(([k,v])=>! /^[a-z0-9_]{1,256}$/i.test(k)||typeof v!=='string'||!v||v.length>512))||!state.approval.removalEtags||typeof state.approval.removalEtags!=='object'||!Array.isArray(state.approval.removals)||state.approval.removals.some((x:unknown)=>typeof x!=='string'||! /^[a-z0-9_]{1,256}$/i.test(x)||typeof state.approval.removalEtags[x]!=='string'||state.approval.removalEtags[x].length>512))||state.cleanup&&(!Array.isArray(state.cleanup.records)||state.cleanup.records.length>100))throw Error();return state;}catch(e){if((e as NodeJS.ErrnoException).code==='ENOENT')return {version:1,source:id};throw new AppError('Datenzustand ungültig oder nicht lesbar; keine Bereinigung.');}finally{await h?.close();}}
 async write(state:SourceState){this.validId(state.source);const root=await this.root(),target=path.join(root,state.source+'.json'),temporary=path.join(root,'.'+randomUUID()+'.tmp'),data=JSON.stringify(state);if(Buffer.byteLength(data)>262144)throw new AppError('Datenzustand zu groß.');let h:Awaited<ReturnType<typeof fs.open>>|undefined;try{h=await fs.open(temporary,constants.O_WRONLY|constants.O_CREAT|constants.O_EXCL|constants.O_NOFOLLOW,0o600);await h.writeFile(data);await h.sync();await h.close();h=undefined;await fs.rename(temporary,target);const dir=await fs.open(root,constants.O_RDONLY);try{await dir.sync();}finally{await dir.close();}}catch{throw new AppError('Datenzustand nicht sicher gespeichert; Bereinigung gestoppt.');}finally{await h?.close();await fs.unlink(temporary).catch(()=>undefined);}}
}
