import { z } from 'zod';
export const rulesSchema = z.object({busyMode:z.enum(['outlook_busy','rfc','all']).default('outlook_busy'),excludeRegex:z.string().max(256).default('^Mittagspause$'),locationIncludeRegex:z.string().max(256).optional(),locationExcludeRegex:z.string().max(256).optional(),locationRegexFlags:z.string().max(5).optional(),transforms:z.array(z.object({field:z.enum(['title','location']),pattern:z.string().min(1).max(256),flags:z.string().max(5).default('iu'),replacement:z.string().max(1024)})).max(32).optional(),includeLocation:z.boolean().default(false),acceptedCount:z.boolean().default(false),floatingTimezone:z.string().default('Europe/Berlin')});
export const sourceSchema = z.object({id:z.string().uuid(),name:z.string().min(1).max(80),kind:z.enum(['upload','file','folder','url','google']),sourceCalendarId:z.string().min(1).max(1024).refine(v=>!/[\x00-\x1f\x7f]/.test(v)).optional(),location:z.string().max(4096).default(''),calendarId:z.string().max(1024).refine(v=>!/[\x00-\x1f\x7f]/.test(v)).optional(),folderMode:z.enum(['aggregate','snapshot']).optional(),snapshotFile:z.string().max(255).refine(v=>/^[^/\\]+\.ics$/i.test(v)&&v!=='.'&&v!=='..').optional(),snapshotClip:z.object({completeExportConfirmed:z.boolean(),boundary:z.enum(['exclusive','protect-boundary']),ordering:z.literal('manual-confirm')}).optional(),clipSeriesMode:z.enum(['strict','preserve-master']).optional(),snapshotScope:z.object({authority:z.enum(['unknown','full','window']),window:z.object({start:z.string(),end:z.string(),timezone:z.string()}).optional()}).optional(),fileHandling:z.enum(['keep','archive','delete']).optional(),immutableFilesConfirmed:z.boolean().optional(),watch:z.boolean().default(false),enabled:z.boolean().default(false),intervalSeconds:z.number().int().min(60).max(604800).default(300),cron:z.string().max(100).optional(),cronTimezone:z.string().default('Europe/Berlin'),rules:rulesSchema.default({})}).refine(s=>!s.watch||s.kind==='folder',{message:'Watch nur für Ordnerquellen.'}).refine(s=>s.clipSeriesMode!=='preserve-master'||s.folderMode==='snapshot'&&!!s.snapshotClip,{message:'Serienerhalt benötigt bestätigten Clip-Snapshot.'}).refine(s=>!s.snapshotClip||s.folderMode==='snapshot',{message:'Clip-Fenster nur im Snapshotmodus.'}).refine(s=>!s.folderMode||s.kind==='folder',{message:'Snapshot nur für Ordnerquellen.'}).refine(s=>s.folderMode!=='snapshot'||!!s.snapshotFile,{message:'Snapshot-Dateiname fehlt.'}).refine(s=>!s.fileHandling||s.fileHandling==='keep'||s.kind==='folder'&&s.immutableFilesConfirmed===true,{message:'Bereinigung benötigt Ordner und bestätigte unveränderliche veröffentlichte Dateien.'}).refine(s=>s.kind!=='google'||!!s.sourceCalendarId,{message:'Google-Quellkalender fehlt.'});
export type Rules = z.infer<typeof rulesSchema>;
export type Source = z.infer<typeof sourceSchema>;
export type EventTime = {date:string;dateTime?:never;timeZone?:never}|{dateTime:string;timeZone:string;date?:never};
export interface TargetEvent {summary:string;location?:string;start:EventTime;end:EventTime;status:'confirmed';transparency:'opaque';visibility:'private';reminders:{useDefault:false};extendedProperties:{private:{icsSync:'v1';source:string;key:string;calendar?:string;origin?:string;desiredHash?:string;mappingHash?:string;hashVersion?:string}};recurrence?:string[]}
export interface Item {restoreEtag?:string;restoreParentEtag?:string;restoreScope?:import('../server/snapshot-preview.js').SnapshotScope;key:string;parent?:string;original?:EventTime;cancel:boolean;clipSeriesEtag?:string;clipSeriesInput?:TargetEvent;approvedCancelEtag?:string;approvedCancelScope?:import('../server/snapshot-preview.js').SnapshotScope;reconcileOrigin?:string;event?:TargetEvent}
export interface Plan {clipWindow?:import('../server/clip-window.js').ClipWindow;sourceRevision?:string;inputFiles?:import('../server/data-store.js').InputFile[];inputMissing?:boolean;snapshotPreview?:(import('../server/snapshot-preview.js').SnapshotPreview&{token?:string});items:Item[];protectedMasterKeys?:string[];stats:{files?:number;components?:number;uids?:number;exceptions?:number;upserts:number;explicitCancellations:number;reconciledCancellations?:number;normalizedClipSeries?:number;clipOccurrencesAdded?:number;clipOccurrencesCancelled?:number;quarantinedSeries?:number;quarantinedGroups?:number;sourceFetched?:number;targetFetched?:number;filesArchived?:number;filesDeleted?:number;filesRetained?:number};warnings:string[]}
export interface Status {ok:boolean;at:string;mode:'preview'|'sync';stats?:Plan['stats'];error?:string;retryAt?:string;automaticPaused?:boolean;running?:boolean;progress?:{fetched:number;changed:number;skipped:number;written:number;pending:number;confirmedEarlier:number;resuming:boolean};sync?:{upserted:number;cancelled:number;absentCancelNoop:number;unchanged:number}}
export interface AppState {sources:Source[];statuses:Record<string,Status>;watchStatuses?:Record<string,{mode:'watching'|'polling'|'settling';error?:string}>;writesEnabled:boolean;oauthConfigured:boolean;calendarConfigured:boolean;defaultCalendarId?:string;ephemeral:true;demo:boolean}

export interface GoogleCalendar {id:string;summary:string;accessRole:'owner'|'writer'|'reader'|'freeBusyReader';primary:boolean;writable:boolean}
